* SHELTER

A "Shell" providing familiar linux Command Line Interface in the Common Lisp REPL
An introduction to Common Lisp by common patterns

The initial interface to a computer is the terminal and shell: poke filesystem, issue command, minimal structure, maximal flexibility.

The vast majority of projects begin in shell:  minimal grand plans, maximal inquiry,
then some abomination of bash or poor perf python grows around that beginning (why not both!).

The aim of shelter is to make that exploratory phase a path which flows directly into CL.
The goal is to make evolution from early inquiry to a fully fledged high perf program easy.

Common lisp provides an interactive REPL, which has comparable attributes to a terminal,
and the majority of shell like functions exist, although they may have arcane names, and be found spread across an expedition of packages.

In shelter, basic shell commands should feel native.
Anybody with programming/bash experience should be immediately at home on the REPL.

The educational parts of Shelter are not meant to be a comprehensive introduction, or the ultimate library.
These are my opinionated selections and frequently used examples that get me productive and learning through use.
Though I do enjoy the sprawling options and obscure tools that common lisp provides,
a focused on-boarding would have helped immensely, this is the practical onboarding I would have wanted to have.

This is a Work In Progress

Initially shell functions can be simple wrappers,
the goal is to eventually have them all in portable common lisp,
and have each doc-string describe the canonical CL approach.

  - Purpose
    - Shelter answers the question: what 20%  does 80% of the work?
      - concepts
      - operations
      - systems and packages
    - Shelter serves as an on ramp to common lisp concepts
      - The setup and discovery of common lisp is an obstacle due to its history and complexity.
      - Getting past this steep initial learning curve to the good stuff of Common Lisp should be made gradually.
      - Assuming that users interested in common lisp have prior linux and bash knowledge, is the key
    - Shelter should ease daily tasks, such that the REPL becomes easier and more useful than bash shell
      - So that projects can begin in the REPL and then grow into their potential

Note: let &&& be "right here completion needed"

* Startup

Nice intro
https://lisp-lang.org/

Mini spec - most used topics and examples
https://lamberta.github.io/minispec/

Questions and discovery
https://lisp-docs.github.io/

** SBCL

steel bank common lisp
https://www.sbcl.org/

install from command line
#+begin_src bash
sudo apt-get install sbcl
#+end_src

** quicklisp

https://www.quicklisp.org/beta/

install from command line
#+begin_src bash
curl -o /tmp/quick.lisp http://beta.quicklisp.org/quicklisp.lisp
sbcl --no-sysinit --no-userinit --load /tmp/quick.lisp \
       --eval '(quicklisp-quickstart:install :path "~/quicklisp")' \
       --eval '(ql:add-to-init-file)' \
       --quit
#+end_src

** ultralisp

https://ultralisp.org/

install from command line
#+begin_src bash
sbcl --eval '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)' --quit
#+end_src

** ocicl

https://github.com/ocicl/ocicl

install from command line
#+begin_src bash
# install ocicl binary to &&&
temp="~/ocicl-temp"
mkdir -p ${temp} && cd ${temp}
git clone https://github.com/ocicl/ocicl.git
cd ocicl
sbcl --load setup.lisp
cd ~ && rm -rf ${temp}

# modify ~/.sbclrc
ocicl setup

# create a "top level" ocicl dir in home
cd ~
sbcl --eval '(asdf:load-system :str)' --quit
#+end_src

** shelter

install from command line
#+begin_src bash
  git clone https://github.com/metarepl/shelter ~/common-lisp/shelter
#+end_src

** spacemacs

https://www.spacemacs.org/

install from command line
#+begin_src bash
    # install emacs
    apt install emacs

    # clone spacemacs
    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
    cd ~/.emacs.d
    git checkout develop

    #copy my dotfile
    temp="~/temp-dotfile"
    mkdir -p ${temp} && cd ${temp}
    git clone https://github.com/metarepl/uncommon-dotfiles.git
    cd uncommon-dotfiles
    cp spacemacs/.spacemacs ~/.spacemacs
    cd ~ && rm -rf ${temp}

    # first start will bootstrap spacemacs
    emacs
    # wait for compilation

    # quit
    SPC q q
#+end_src

basic spacemacs dotfile guide

  - ~/.spacemacs configures spacemacs and can be modified to suit your needs
  - search for "dotspacemacs-configuration-layers"
  - this is a list of "layers" spacemacs provides
  - for more options click "layers list" on the homepage

** use shelter

- in bash open spacemacs
  - emacs
- open scratch buffer
  - SPC b s
- actvate lisp mode
  - SPC SPC lisp-mode
- activate REPL
  - , '
- at the prompt evaluate commands

evaluate in the REPL
#+begin_src lisp
  ;; testing
  (print "hello lisp")

  ;; load shelter
  (asdf:load-system :shelter)
  (use-package :shelter)

  ;; use shelter
  (ls)
  (cd)
  (pwd)
  (shelter:pwd)

  ;; to see available functions and variables in shelter
  ;; (shelter: DOWN-ARROW

  ;; to get more info
  (describe 'pwd)
#+end_src

* System Structure

- A SYSTEM is a collection of packages,
- A PACKAGE is a collection of symbols,
- A SYMBOL can be a variable or a function,
- Symbols are exported by the package declaration.
- Packages are organized by the system declaration

Common lisp gave these names to this nested structure of code and project organization long long ago when the earth was green.
Unfortunately, incumbent language designers chose conflicting terminology.
Restated in more familiar terms: A package (in lisp: system) is a collection of namespaces.
A namespace (in lisp: package) is a collection of exports.

ASDF is another-system-definition-facility

The system declaration is easy to use to organize packages,
but it also declares system dependencies, organizes source code and manages the build order.
The ASDF system declaration is used to facilitate the build system which is part of ASDF.
This build system is like make, but far easier to use in addition to being more flexible and more powerful.
By beginning with ASDF systems, the whole dependency tree of systems can be compiled into the image,
with one command:

#+begin_src
  (asdf:load-system :an-easy-system) ;; the system and transitive dependencies are discovered and loaded
#+end_src

Note:
ocicl and repocicl are systems that extend asdf. When a dependency is not locally available they will do discovery and download.
Without ocicl and repocicl, asdf does not download.

** Systems

  - Lisp systems
    - system definition is declarative
    - can contain meta data of the project similar to debian packages
    - possible to create multiple systems per asd file
    - defsystem is capable of complex loading order dependencies

  - it is the easy default for the directory name to match the asd file name, but not absolutely necessary.
  - ie ./my-project/my-project.asd
  - it is required that the asd file name match the defsystem &&&confirm

  an example simple system
  #+begin_src lisp

    ;; with minimal components in flat file system
    ;; - my-project (directory)
    ;;   - my-project.asd
    ;;   - my-project.lisp

    ;; my-project.asd
    (defsystem :my-project
      :depends-on (:alexandria :str)
      :serial t
      :components ((:file "my-project")) ; implicitly a .lisp file

    ;; my-project.lisp
    (in-package :cl-user)

    (defpackage #:my-package
      (:use :cl)
      (:export :my-function))

    (in-package :my-package)

    (defun my-function ()
      "an exported function"
      (print "hello world"))

      #+end_src

  an example well structured system
  #+begin_src lisp

    ;; with components in hierarchical file system
    ;; - my-project (directory)
    ;;   - my-project.asd
    ;;   - package.lisp
    ;;   - README.org
    ;;   - src
    ;;     - utils.lisp
    ;;     - my-project.lisp
    ;;   - test
    ;;     - tests.lisp

    ;; my-project.asd
    (defsystem :my-project
      :depends-on (:alexandria :str)
      :serial t
      :components ((:file "package")
                   (:static-file "README.org")
                   (:module "src"
                    :components ((:file "utils")
                                 (:file "my-project")))
                   (:module "test"
                    :components ((:file "tests")))))

    ;; package.lisp
    (in-package :cl-user)

    (defpackage #:my-package
      (:use #:cl)
      (:export #:my-function))

    ;; my-project.lisp
    (in-package :my-package)

    (defun my-function ()
      "an exported function"
      (print "hello world"))

  #+end_src

** Package concepts

  - initially the repl places the user in the cl-user package
    - cl-user contains basic functions variables and macros, defun etc

  - a package is a first class object
  - a package is just a container to group symbols together
    - a symbol is a basic type denoting a function or a variable or other things
  - used as namespaces
  - possible to create multiple packages per system
    - naming packages by functionality is useful to organize functions for discovery
    - eg my-package (exports all)
    - my-package/utils or my-package/config (exports specific symbols)
  - packages don't have to be defined in a package.lisp file
    - you can define it in any file then in-package to use it
  - packages and files are independent
    - a file can go in-package then define this-function
    - then go in-package to define another function
    - the functions' symbols will be found in their respective packages
  - you can do what you want

  - modern style
    - defines packages in a single file package.lisp
    - names sub packages with /
      - eg my-package/subset
    - uses a single package per single file of code

#+begin_src lisp
  (in-package :cl-user) ; make cl-user package available now

  (defpackage :my-package
    (:use #:cl) ; :cl bring cl-user symbols into my-package
    (:export #:*exported-symbol*))

  (in-package :my-package)

  (defparameter *exported-symbol* 'hello)

  ;; check available symbols in a package
  (do-external-symbols (sym :cl)
    (print sym)) ; show current symbols ~1000

  (do-external-symbols (sym :my-package)
    (print sym)) ; our one symbol
#+end_src

** Package use

regarding #:some-name vs :some-name in package definitions.
Don't worry to much about this,
just know that :some-name always creates a symbol and #:some-name doesnt so #: keeps packages less cluttered

load some packages
#+begin_src lisp
  ;; preferably use ocicl and asdf
  (asdf:load-system :cmd)
  (asdf:load-system :str)
  (asdf:load-system :file-finder)
  (asdf:load-system :com.inuoe.jzon)

  (ql:quickload :cmd)
  (ql:quickload :str)
  (ql:quickload :file-finder)
  (ql:quickload :com.inuoe.jzon)

#+end_src

Package symbols interactions
#+begin_src lisp
  ;; package declaration
  (defpackage :my-package
                                          ; provide alternate names for the package
    (:nicknames #:mypk #:metarepl.examples.my-package)
                                          ; doc
    (:documentation "doc string for the package")
                                          ; whole package import, discouraged except for :cl
    (:use #:cl #:str #:cmd #:file-finder)
                                          ; &&&
    (:shadow &&&)
                                          ; shadowing other symbols, declares dominant function
    (:shadowing-import-from #:cmd #:current-directory)
                                          ; specific symbol import to this package, encouraged
    (:import-from #:uiop
                  #:subdirectories #:directory-files :getcwd)
                                          ; rename package and or function, nick original-name
    (:local-nicknames (#:jzon #:com.inuoe.jzon))
                                          ; export functions and params to the my-package: name space
    (:export
     #:my-function
     #:*my-parameter*))
#+end_src

Package movement
#+begin_src lisp
  ;; enter package
  (in-package :my-package) ; Also enter this in the REPL (if you want it there)

  ;; do things on the repl or in the file

  ;; to leave
  (in-package :cl-user)

  ;; do other things

   ;; :my-package maintains state
#+end_src

** naming convention

Naming of systems and packages has very few constraints,
these are patterns that are useful.
None of these patterns are rules at all, none of these characters are required or special at all.
It's common lisp you can do what you want.

*** repo name

When the asd file name does not match the repository name (which becomes the directory name),
you will need to symlink the asd file into a place asdf searches, like ~/common-lisp.
This use pattern gives manual control over what is discovered: clone into some dir, symlink the asd file.
This also separates the concerns of sorting repos from discovering systems.

- github.com/metarepl/my-project
  - metarepl.category-specifier.my-project.asd
  - package.lisp
  - src/my-project.lisp

For utility libraries, I make the repository name into the long version.
Same use pattern of clone and symlink.
This makes many small libraries easy to store, sort, navigate and recall what they do.
Its clunky and verbose, but it works like a charm.

- github.com/metarepl/metarepl.category-specifier.my-project.asd
  - metarepl.category-specifier.my-project.asd
  - package.lisp
  - src/my-project.lisp

For polished libraries, where user ease is primary,
the repository name (which becomes the dir name),
the asd file name, and its defined system name,
and the package name should all be the same.
This use pattern only requires cloning into somewhere asdf searches, and discovery will just work.

- github.com/metarepl/shelter
  - shelter.asd (which defines a system :shelter)
  - package.lisp (which defines a package :shelter)
  - src/shelter.lisp

For libraries with short and polished names,
optionally use package nicknames to also use the long categorized name for consistency and discoverablity

*** system name

#+begin_src lisp

  (asdf:defsystem "metarepl.category-specifier.my-project" ;; must match the asd file name
    :depends-on (:other-asdf-system)
    :serial t
    :components ((:file "package")
                 (:module "src"
                  :components ((:file "cool-proj")))))

#+end_src

*** package name

#+begin_src lisp

  (defpackage #:my-project
    (:use #:cl)
    (:export #:*my-symbol*
             #:my-function))

#+end_src

** manual imports and exports

defpackage does a nice job of setting things up for us but if you want to bang around in an image,
and really move the furniture around, there are commands where you can do it all manually

#+begin_src
(make-package :my-package)
(in-package :my-package)

*package* ;; current package

(rename-package :my-package &&&)
(add-package-local-nickname &&&)

(use-package :ppcre)
(unuse-package :ppcre)

(import 'ppcre:regex-replace)

(shadow 'some-sybol)
(shadowing-import 'some-symbol)

(export '*exported-symbol*)
(unexport '*exported-symbol*)

(intern 'a-symbol)
(unintern 'a-symbol)
#+end_src

heres a good read on what is going on in defpackage  https://flownet.com/gat/packages.pdf

** manual system loading

interacting with asdf
#+begin_src lisp

  ; load a file without asdf
  (load #P"/path/to/my-file.lisp")

  ;; get the location of the system
  (asdf:locate-system :shelter)

  ;; get the system itself
  (asdf:find-system :shelter)
  (inspect *) ; check out the details of the system returned in the previous command
  ;; q RET to leave inspect mode

  ;; load system definition
  (asdf:load-asd "str.asd") ;  can use exact path
  (asdf:load-system :shelter) ; will load but not download dependencies

  ;; get list of dependencies
  (asdf:system-depends-on (asdf:find-system "str"))

  (defparameter *str-deps* *) ;; grab the list returned previously

  ;; begin it all again and explore ALL the dependencies
  (asdf:find-system (first *str-deps*))

#+end_src

** automatic system downloading

quicklisp is convenient and commonly seen in examples.
I dont recommend it except for quick scripts.
Using ocicl is better than quicklisp,
because it make downloads secure,
but it also makes downloading appear native to asdf commands.
Then any packages that uses asdf for compilation or deployment, gains online system discovery as well.
When your build system can do deployment and discovery and compilation and its transitive through the whole system, well, its pretty slick.


#+begin_src lisp
  ;; with quicklisp
  (ql:quickload :str) ; recursively loads dependencies and downloads

  (in-package :str) ; enter the package to use internal functions
  (use-package :str) ; bring external symbols from str into the current package

  ;; with ocicl this is equivalent to quickload
  (asdf:load-system :str)
  (use-package :str)

#+end_src

* Lisp Concepts
** Intro

In the core of lisp, the meta circular evaluator was discovered by John Mcarthy.
From system primitives lisp develops a self evaluator, and then builds out to
create the language. The implication of this is that Lisp is built ON lisp, and
when you work with it, you will be also be working ON the language.

The correct perspective is that you are outside a set of tools or a material,
refining the tools, building and forming the material to move up toward your target.
This material is the abstract syntax tree itself.
The tools are the ability to shape the syntax, as if all changes were native to the language.
Expression is unbounded.

This is profoundly different from working IN a language.
For other programming scenarios, we work within the constraints of the language.
We work ON a program, IN a language, the language sets the boundary of expression.

When we work on lisp we are inside the image.
Outside the image is the OS handling multi tasking.
The running lisp image is best though of as like an OS, not quite, but almost.
Inside the image is a place for programs, we are not restricted to a single program.
Multiple programs from one or multiple files can exist within the image at one time.
The order of function definition does not matter, the functions are compiled into the image in memory.

The running image has an interactive shell like repl, functions, programs, scheduled tasks.
Individual functions can be hot recompiled while the image runs.
When the goal is reached, that image can be exported as is, for distribution.
That could be a script, an app, or an OS.

Essentially, we have at our disposal a language we can modify to fit any domain specific purpose,
within a live system that we can interactively modify to contain the activity required,
including running multiple programs simultaneously.
It is not quite an OS, but almost, hence the terminology for software units as 'systems'.

** Symbol

Symbols are a distinct and fundamental type

Symbols are fundamental to Lisp's property of "code is data, data is code".

A symbol in Common Lisp is a data object with four components:
1. Name - a string
2. Value - any Lisp object (when used as a variable)
3. Function - a function object (when used as a function name)
4. Property list - an association list for arbitrary properties

Creating symbols
#+begin_src lisp
'foo               ; => FOO (symbol)
(intern "BAR")     ; => BAR (creates or finds symbol)
(make-symbol "X") ; => #:X (uninterned symbol)
#+end_src

Symbols serve multiple roles:

 1. Names and Identifiers

Symbols name variables, functions, and other entities.
#+begin_src lisp
  (defvar *count* 0)  ; *COUNT* is a symbol naming a variable

  (defun add (x y)    ; ADD is a symbol naming a function
    (+ x y))
#+end_src

 2. Self-Evaluating

in quoted context the symbol is not evaluated, or rather, it evaluates to itself
#+begin_src lisp
'hello  ; => HELLO (the symbol itself, not its value)
#+end_src

 3. Interned vs Uninterned

Interned: Registered in a package, accessible by name

Uninterned: Not in any package (printed as #:NAME)

 4. Symbols as Data

 Used in pattern matching, as keys, and for symbolic computation:

#+begin_src lisp
(get 'color 'value)           ; property access
(eq 'yes 'yes)                ; => T (same symbol)
#+end_src

** Image

The image is the program, running in memory, it can be exported and reloaded.
It is live in that parts of the image can be dynamically modified.
An image can contain multiple systems, and multiple packages.

The image is a snapshot of the entire runtime state of a running Lisp system, including:
- system configuration - reader settings, package definitions, loaded libraries
- loaded code - compiled functions, macros, packages
- runtime state - variable values, data structures, object instances

- Incremental Development: You modify code while the program runs, without restarting.
  - Changes are compiled and integrated immediately.
- Persistence: You can save image and restore it later
- Fast startup: Loading an image is much faster than recompiling code
- Deployment: Applications are often distributed as executable images

  custom environments with pre loaded tools
#+begin_src lisp

  ;; Start with base image
  ;; Load libraries
  (asdf:load-system :big-system)

  ;; define functions and parameters

  ;; Save an image as a development snapshot
  (save-lisp-and-die "myapp.core")
  ;; Start from an image
  $ sbcl --core myapp.core

#+end_src

 application deployment
#+begin_src lisp

  ;; Start with base image
  ;; Load libraries, define functions
  (defun my-app () ...)

  ;; Test and debug interactively
  (my-app)

  ;; Fix bugs without restarting
  (defun my-app () ... fixed version ...)

  ;; Save the working state
  (save-lisp-and-die "my-app" :executable t)

#+end_src

the exported image is a standalone executable for distribution

** Incremental and Live

Don't blow up the factory to tighten a single bolt on a conveyor.
Why recompile an entire program to modify a function?
Why even stop the program to modify a function?

In common lisp compilation and recompilation of a single function,
can occur as the rest of the program runs.
And the running program will use the new function definition.
This incremental compilation is analogous to tightening a bolt, while the factory runs.

Errors don't unwind the stack, they do stop execution right at the moment it occurs.
You can then inspect the stack, identify the problem, redefine the function, variable, or entire system.
Then resume execution using the updated definition.

Inspection of the stack is similar to browsing old internet, it is clickable browsable text.
I LOVE getting errors, its like having a print statement showing the state of my program
at every function and variable (all the way down to memory addresses if you want to go that far).
Then surfing my program to the source, fixing just that bit, and carrying on from there.

** Differences

Density

Lisp code is very dense, if you are struggling to read something.
Slow. Down.
You dont read math as fast as a novel.
Consider how much is being done and expressed,
and realize you might be trying to read the equivalent to hundreds of lines of java.
Then take the time to understand.

Position

A lot of syntax sugar and symbol use is just not there.
This is a part of the density, position has meaning.
Meaning is found in the position of an element.
eg. the first position is the function call .
the second form in an if is the else clause.
there are no commas in a list.

On the other hand, position of computation is very flexible, you can put what you need to do where you need to do it.
If a form evaluates to the right argument, it can be placed there, even if it contains arbitrary complex sub forms.
This becomes apparent when you need to modify a function for an edge case.
There ususally appears a precise postion in the code where you can nest some logic to deal with the
specific cases, without substantially affecting the original.

Flows

Control flows down, values flow up.
Code can be understood bi-directionaly.
This counter flow pattern also occurs in systems in biology by the way.
You might come across code with a section of logic placed below only one variable assignment,
Understand that this is likely catching an edge case which flows down, through the control, and the selected value flows up to
the assignment.
Similarly control enters the function, flows down according to the arguments,
and various computed values flow up and are combined.
The final return value should be though of as leaving the top left of the function, not the bottom right.

Independence

many operations we assume are bound together in other languages are independent in common lisp.
- packages import is independent of use
- in-package for the file of code is indpendent of in-package for the REPL
- (uiop:chdir ...) is independent of the parameter default-directory-defaults
- &&&

Many granular steps are available and required to precisely specify the system,
none of this is particularly verbose, but it does require a change of details to
attend to. If something is not working as expected, I check what actions I have
assumed are accomplished by some explicit command.

* Lisp and REPL Operations
** Pathnames

Common Lisp is older than any of the file systems in use today, its pathname
system is still more powerful and still relevant to every possible system. That
is a clue that there are some significant differences in how this is being
acomplished, some will not be intuitive.
https://lispcookbook.github.io/cl-cookbook/files.html
is essential reading, twice.

These tools cover far MORE than linux can acomplish with a filesystem. Clarifying
and reducing initial friction for file and dir ops is one of the major objectives of
this project.
- https://github.com/Shinmera/pathname-utils
- https://edicl.github.io/cl-fad/
- https://github.com/Shinmera/filesystem-utils
- https://shinmera.github.io/file-attributes/
- https://osicat.common-lisp.dev/manual/osicat.html
- https://github.com/fosskers/filepaths
- https://codeberg.org/fourier/ppath
- https://asdf.common-lisp.dev/uiop.html

#+begin_src lisp
                                          ; pathname objects are not strings
  #P"/bin/"
  ;; subcomponents can be manipulated individually
  ;; inspect &&&

  ;; ~ for home
  (user-homedir-pathname)

  ;; . for this location
  (uiop:getcwd)


#+end_src

Override default-pathname-defaults
#+begin_src lisp
  ;; this guy causes issues if Im not paying attention
  (print *default-pathname-defaults*)

  ;; &&&note elsewhere how (print (foo)) is transparent, prints and passes (foo) through
  ;; very nice for debugging

  (uiop:with-current-directory ("/bin")
    (print (uiop:getcwd))
    (directory-files "./"))

  (print (uiop:getcwd))

  (with-current-directory ("/tmp")
    (print (uiop:getcwd)))
#+end_src

** Dir Operations
Some operations use the default-pathname-defaults variable to establish the starting point, not all.
Online commentary defining paths from root is guaranteed consistent. I just set it consistently, it is wrapped in the (cd "str") function.

#+begin_src lisp
  (defparameter *my-starting-dir* (uiop:getcwd))

  ;; ls -d
  (directory "*") ; the syntax is badly documented(online) check

  (uiop:subdirectories (user-homedir-pathname))
  (uiop:subdirectories #P"/home/user/")
  (uiop:subdirectories "/home/user/")

  ;; pwd
  (uiop:getcwd)

  ;; cd
  (uiop:chdir #P"/path/name")
  (setf *default-pathname-defaults*(uiop:getcwd))


  ;; path to string
  (namestring "/home/user/")
  (namestring "#P/home/user/")
  (namestring (user-homedir-pathname))

  ;; string to path
  (pathname "/home/user")
  (pathname "/home/user/")
  (pathname #P"/home/user/")
  (pathname (user-homedir-pathname))


#+end_src

** find-dir

find-dir takes a list of paths and fuzzy filters directories, if depth is set it descends into directory tree,can be sequentially applied to its own output.

arg : default action : description
root : '(#P\"/\") : a list with paths or a path in #P or string form
depth : 0 : an integer for retrieval depth below roots, default 0 goes no deeper for filtering root list
keep : all : space delimited words to separately(additive to set) fuzzy filter in
drop : none : space delimited words to separately(additive to set) fuzzy filter out, applied after keep
report : none : set true for reporting on processing, big ass reports if depth is large
n-test : off : integer for required num of paths in output list, error and report if not "

#+begin_src lisp

  (find-dir :keep "lib opt" :drop "etc lib gnu" :depth 2)
  (find-dir :report t :keep "lib opt" :drop "etc lib gnu" :depth 2)
  (find-dir :n-test 6 :depth 3 :keep "opt" :drop "gnu"  )
  (find-dir :drop "chrome"
            :root (find-dir :depth 2
                            :keep "opt"
                            :drop "gnu"))


#+end_src

** file-finder
https://github.com/lisp-maintainers/file-finder/

convenience wrapper
=(finder (name~ "string")) => #F"file_object.type"=
granular control
=(finder* :predicates (name~ "string" ) :root <string | #P> ) => #F"file_object.type"=


Finder predicates
path
- =path~= matches when one of the path elements is contained in the file path.
- =every-path~= same checks on the file path, but uses a logical and.
- =path$= matches when one of the path suffixes matches the file path.

file name
- =name== matches when one of the names matches the file name (case sensitive).
  - full file name
- =iname== matches when one of the names matches the file name (case insensitive).
- =name~= matches when one of the names is contained in the file basename (and not the whole path), case sensitive.
  - partial name
- =iname~= matches when one of the names is contained in the file, case insensitive.
- =every-name~= same checks on the file basename, but uses a logical and.

extension
- =extension== matches file extensions
  -  full exact

recur predicates
- =depth<= matches when the argument file is in a subdirectory of ROOT less deep than LEVEL.
- =hidden?= return t if this is a hidden file

#+begin_src lisp
  (ql:quickload :file-finder)
  (use-package :file-finder)



  ;; basic
  (file-finder:finder* :root "/home/user/Downloads")
  (file-finder:finder* :predicates (file-finder:extension= "txt")
                       :root "/home/user/Downloads")
  ;; recur predicates
  (file-finder:finder* :predicates (file-finder:extension= "txt")
                       :recur-predicates (complement #'file-finder:hidden?)
                       :root "/home/user/Downloads")

  ;; predicates AND
  (finder* :predicates (list (name~ "test")
                             (complement (path~ "exclude"))
                             (extension= "txt"))
           :root "/home/user/Downloads")

  ;; call with find-dir for root
  (file-finder:finder* :predicates (file-finder:extension= "txt")
                       :root (first (find-dir :n-test 1
                                              :keep "Downloads"
                                              :depth 3)))


  ;; wrapper set interpretation is different
  ;; and
  (finder (<ff>)(<ff>))
  ;; or
  (finder (list (<ff>) (<ff>)))

  ;; convert results to string to use set operations
  ;; &&& is there a better way
  (mapcar #'namestring (finder &&&))
  (set-difference *), (union *)

  (set-difference
   (mapcar #'path (finder (path~ "index") (path~ "indices") (extension= "tif")))
   (mapcar #'path (finder (path~ "tiles")))
   :test #'equal)
#+end_src

** File Operations

#+begin_src lisp
  ;; ls -f
  (directory-files &&&)

  ;; &&& move rename delete
#+end_src

** File IO

#+begin_src lisp
  (defparameter *file* #p"/home/user/test.txt")
  (print *file*)
  (uiop:read-file-lines *file*)

                                          ; open files
  (with-open-file (stream "test.txt" :direction :output
                                     :if-exists :supersede)
    (write-line "Hello, World!" stream))

  (with-open-file (stream "test.txt"
                          :direction :input
                          :if-does-not-exist :error)
    (let ((contents (make-string (file-length stream))))
      (read-sequence contents stream)
      (print contents)))

  (with-open-file (stream filename)
    (iter (for line = (read-line stream nil))
      (while line)
      (format t "~A%~%" line)))
#+end_src

** Getting Help

quicksearch
https://github.com/lisp-maintainers/quicksearch

TODO (help) and (help "symbol")
should be an interactive menu describing the options/ letting user go on to any or all sub
(help "help") should go give detailed descriptions of each  option

package help
symbol help
namespace help

#+begin_src lisp
  ;;search quicklisp dists for a package
  (ql:system-apropos "find-me")
  ;;search all dists and github for a package
  (quicksearch:quicksearch "find-me")

  ;;inspect &&&
  (inspect "string")
  ;;describe&&&
  (describe "string")
  ;;apropos&&&
  (apropos "string")
  ;;documentation&&&
  (documentation "string")
#+end_src

** REPL and error and messages
** Interfacing emacs/code/REPL
pushing parens ahead around next form
go to source
l to move back in stack trace
slime-cd to change location

- editor functions
  - https://lispcookbook.github.io/cl-cookbook/emacs-ide.html
  - C-c C-k to compile and load
  - C-c ~
  - Evaluate single form in place: =,-e-c=

- interact with the repl
  - &&&
- move around in error message
  - &&&
- Observe objects:
  - (inspect "string")
  - (describe "string")
  - (apropos "string")
  - (documentation "string")

* Syntax Concepts
** Parentheses are just trees

Functions within functions within functions. Look inward.

Don't look at the parens, thats the computers job so don't do that,
instead focus on the indentation and see the tree.
The abstract syntax tree is immediately available to the programmer and to the program

#+begin_src lisp

  (+ (* 3 4) (- 10 5) (/ 12 (+ 2 2)))

  ;; math is just a tree of operations
  (+ (* 3
        4)
     (- 10
        5)
     (/ 12
        (+ 2
           2)))
#+end_src

#+begin_src lisp

  (defvar *tree* '(A(B(D)(E))(C(F)(G)(H))))

  ;; data is just a tree of nested relationships
  (A
   (B
    (D)
    (E))
   (C
    (F)
    (G)
    (H)))

#+end_src

#+begin_src lisp

  ;; a function is just a tree of steps and branches
  (defun traverse (tree)
    (when tree                        ;stops when nothing
      (if (atom tree)                 ;test for a leaf node
          (print tree)                ; true, print the leaf
          (progn                      ; else, do these things
            (print (car tree))        ;  print parent before decending
            (traverse (cdr tree)))))) ;  descend into the remainder of the tree

#+end_src

#+begin_src lisp

  ;; a program is just a tree of processes
  (defun program ()
    (do-the-thing)
    (or (do-one-other-thing)
        (do-the-remaining-things)))

#+end_src

Q: If a program is just trees of trees, and data and functions are just trees
and we can have code that walks a tree
does that mean a program could go into a program?
could a program treat a program like data and change it?

A: code is data, data is code, and yes after all it is just a tree

Wooooaaaahh Duuuuude

** Variables
defparameter vs defvar, both set global variables
defparameter is mutable
defvar is immutable

let is lexically scoped, valid within it range
let can dynamically redefine a global variable temporarilly

#+begin_src  lisp
(defparameter *my-param*) ;error requires binding
(defparameter *my-param* nil) ; bound to NIL
(defparameter *my-param* '()) ; bound to NIL
(defparameter *my-param* 42
  "doc for my-param")
(defparameter *my-param* 47
  "doc for my-param") ; rebound


(defvar *my-var*) ; success unbound at this point, not even nil
(defvar *my-var* 124) ; bound at this point
(defvar *my-var* 1) ; immutable, but no error on attempt

(let (a b)
  (setf a 1
        b 2)
  (format t " a: ~A b: ~A~&" a b))
(let ((a 3)
      (b 4 ))
  (format t " a: ~A b: ~A~&" a b))

(let* ((a 3)
       (b 4)
       (c (+ a b)))
  (format t " a: ~A b: ~A c: ~A~&" a b c))

(format t "outside the lexical scope before the let *my-param*: ~A~&" *my-param*)
(let ((*my-param* 11))
  (format t "only within the lexical scope of the let *my-param*: ~A~&" *my-param*))
(format t "outside the lexical scope after the let *my-param*: ~A~&" *my-param*)
#+end_src

** Conditions

#+begin_src  lisp
  (if (test)
      (then) ; or prog1 for then,continuing
      (else))

  (when (test)
    (then)
    (continuing)) ; implicit progn, no else
  ;; (unless) compliment of when

  (not (test)) ; compliment of test


  (cond ; returns first true block
    (test
        logic0
      logic1
      )
    (t :default))

  (case a
    (1
     :its1)
    (t :default))

  ;; conditional on environment
  *features* is a list of keywords anyone can add to it
  (push :my-feature *features*)
  #+unix
  (print "we are on unix")

  #-foo
  (print "of course there is no foo feature")

  #+(and unix my-feature)
  (print "we are on unix working on my-feature")
#+end_src
** args

#+begin_src lisp
  ;; arguments
                                          ;ordered binding
  (defun example-function (required &optional (optional-arg nil optional-arg-supplied-p))
    (if optional-arg-supplied-p
        (format t "Optional argument was supplied: ~A~%" optional-arg)
        (format t "Optional argument was not supplied~%")))
                                          ; :keyword binding
  (defun example-function (&key (keyword-arg nil keyword-arg-supplied-p))
    (if keyword-arg-supplied-p
        (format t "Keyword argument was supplied: ~ A~%" keyword-arg)
        (format t "Keyword argument was not supplied~%")))

  ;; &&& note on the undefined combination ? &optional &rest
  ;; &&& &rest &body etc
#+end_src

** functions

#+begin_src lisp
  ;; declaration
  (defun hello ()
    "docstring for hello"
    (format t "hello ~A" (uiop:getenv "USER")))
  (hello)

  ;; local functions
  (defun example-flet ()
    (flet ((local-func (x) (* x 2)))
      (local-func 5)))

  (defun example-labels ()
    (labels ((a () (print "In A")))
      (a)))

  (defun example-labels-mutual ()
    (labels ((a () (print "In A"))
             (b () (a)))
      (b)))




(defun hello (name &optional happy) ; optional nil by default
  (format t "hello ~A~&" name)
  (if happy ; when truthy
    (format t ":)")
    (format t ":(")))

(defun hello (name &key (happy "default value" happy-p))
  "doc string"
  (format t "hello ~A~&" name)
  (when happy-p ; when supplied
    (if happy
        (format t ":)")
        (format t ":(")) ))

(defun mean (x &rest numbers)
  "compute mean to demonstrate variadic num of args"
  (format t "&rest yields a list. numbers: ~A~&" numbers)
  (/ (apply #'+ x numbers)
     (1+ (length numbers))))

,-h-h slime-describe-symbol
(apropos "hello") ; loaded in image
(documentation 'hello 'function) ; a symbol
(documentation #'hello 'function) ; a function
;; it is meaningfully different to inspect the symbol vs the function
(inspect 'hello) ; show symbol attributes
(inspect #'hello) ; show function bindings
;; additionally ' mostly refers to toplevel bindings while #' respects lexical environment, flet etc
;; a source of subtle bugs
(describe #'hello) ; usually this is what you need

flet is like let, must be independent
labels is like let*, can refer to each other

;;multiple return values
(defun my-multiple-returns ()
  (let ((a 1)
        (b 2)
        (str "my-string"))
    (values a b str)))

  ;; not a list or tuple
(my-multiple-returns) ; => 1, 2, "my-string"
;; the return value is the first of values
CL-USER> * ; => 1
(nth-value 2 (my-multiple-returns))
(multiple-value-bind (0th 1th) ;  bind to local variables in order,  can bind part or all
    (my-multiple-returns)
  (print 0th)
  (print 1th))

;; higher order functions
(defun compute (x y &key (operation #'+))
   (funcall operation x y))
(compute 1 2)
(compute 1 2 :operation #'-)

(member "foo" '("foo" "bar"))
(member "foo" '("foo" "bar") :test #'string-equal)

(lambda (x) (1+ x))
CL-USER> (funcall * 2)

(compute 4 2 :operation (lambda (x y) (+ 10 x y)))

(defun generate-adder (step)
  (lambda (x)
    (+ x step)))

(generate-adder 10)

funcall and apply

;; closures
function closes over the environment

(let ((counter 0))
  (defun counter-inc ()
    (incf counter))
  (defun counter-init ()
      (setf counter 0))
  (defun counter-value ()
    counter))

(counter-inc)
(counter-value)
(counter-init)

;; returning closures
(defun make-looping-counter (limit)
  (let ((counter 0))
    (lambda ()
      (if (>= counter limit)
          (setf counter 0)
          (incf counter)))))
(defparameter *counter-to-2* (make-looping-counter 2))
(funcall *counter-to-2*)
(inspect *counter-to-2*)

;; setf functions
(let ((counter 0))
  (defun counter-inc ()
    (incf counter))
  (defun counter-init ()
      (setf counter 0))
  (defun counter-value ()
    counter)
  (defun (setf counter-value) (new-value) ; reuse accessor, supply value and any accessor arg
    (setf counter new-value)))

(counter-init)
(counter-inc)
(setf (counter-value) 6) ; setf the location provided by the accessor
(counter-value)


#+end_src

** returns

#+begin_src lisp
  ;; let return
  (let ((a 3)) a) ; => 3
#+end_src

** Errors and Handling
#+begin_src lisp

  ;;simple errors
  (error "This is an error message")
  (error "Problem with x=~D and y=~S" x y)
  ;;specific error types:
  (signal 'type-error (list :expected-type 'number :datum "not a number"))
  ;;For custom errors, define a condition and use `error` with it:
  (define-condition my-custom-error (error) ())
  (error 'my-custom-error)

  ;; create an error
  (error "Signals an error. The arg was: ~A" arg)
  (warn "carefull") ; no debugger
  ;; create object
  (make-condition 'simple-condition ) ; type one of: 'warn 'error 'simple-condition
  ;; signal it
  (signal *)
  signal then handle not throw catch

  (ql:quickload :log4cl)
  (defun f1 (&optional (arg 'nil))
    (error "Signals an error. The arg was: ~A" arg))
  (defun f2 ()
    "handle conditions with handle case"
    (handler-case
        (f1)
      (error (c) ; c for the condition we want to handle
        (log:info "We got an error: ~A" c))))

  (defun w1 ()
    (warn "Warning"))
  (defun f2 ()
    "handle conditions with handle case"
    (handler-case
        (w1)
      ;;doesnt catch warnings
      (error (c) ; c for the condition we want to handle
        (log:info "We got an error: ~A" c))
      (warning (c)
        (log:info "we got a warning: ~A" c))))

  ;; catch errors
  ;; handler-case
  ;; define errors
  ;; ignore-errors
  ;; unwind-protect
  ;; handler-bind
#+end_src

** Macros
#+begin_src lisp


macros do not evaluate their arguments, it is passed as is to the macro process
macros expand to function calls at compile time


(defmacro cube (x)
  `(* ,x ,x ,x))
(cube 2)

;;quote
;; quote does not evaluate its argument.

(list 1 a 2 b) ; > error on a unbound
(quote (list 1 a 2 b)) ; > (LIST A etc) list of symbols
'(list 1 a 2 b) ; > same

(list :a 1 :b 2) ; > (:A etc)
'(:a 1 :b 2) ; > same

(quote (list :a 1 :b 2)) ; > (LIST :A etc)
(eval (quote (list :a 1 :b 2))) ; > (:A etc) full circle

(let ((a 1)
      (b 2))
  (list 'a a 'b b)) ; > (A 1 B 2)


;;backquote and comma
;; do not require macros to use bq and comma
(let ((a 1)
      (b 2))
  `(:a ,a :b ,b)) ; > (:A 1 :B 2)

;; how to spot you are using a macro
non reqular lisp syntax eg loop macro
non regular paren nesting eg let
starts with 'with' eg with open file
new variable bindings eg dolist

;;macros vs functions

macros can not  be used as HOF
funcall, mapcar, apply etc
(defmacro cube (x)
  "you dont need a macro for this"
  `(* ,x ,x ,x))
(mapcar #'cube (list 1 2 3 4)) ; > error macro not function

redefining a macro requires recompiling all functions that use it to be updated
a macro is not called at runtime, because it expands to code at compile time
(defmacro madd (x)
  `(+ 1 ,x))
(defun adder (x)
  (madd x))
(adder 1) ; > 2, even if we recompile madd, must recompile adder to update

slime-macroexpand-all will reveal that the macro has been included in the function at compilation
slime-who-calls functions
slime-who-references symbols
slime-who-macroexpands macros
  jumps to a file, which we may C-c C-k  slime-compile-and-load to recompile all
  but you probably dont need a macro. use them lightly

;; comma-splice
does not require a macro to use

(list :params (loop for i to 2 collect i)) ; => (:PARAMS (0 1 2))
`(:params ,@(loop for i to 2 collect i)) ; => (:PARAMS 0 1 2)

(defmacro mrest (@rest rest)
  (format t "rest is: ~S" rest)
  ~(progn
     ,@rest))

;;body

(defmacro with-body (&body body)
  `(progn ,@body))
(with-body
  (print :body))

(defmacro my-dolist ((var expr) &body body)
  `(loop for ,var in ,expr do
         (progn
           ,@body)))
(my-dolist (x '(1 2 3))
  (print x))

;;
(defmacro with-echo (&body body)
  `(format nil "the result of ~S is ~S"
           (quote ,@body)
           (progn ,@body)))
(with-echo (+ 1 1))

;; gensym
subtle bugs due to variable capture without this

;; call-with pattern
makes reasoning and testing macros easier

(defun call-with-repeat (times function)
  (loop for x from 1 to times do
        (funcall function)))
(defmacro repeat (times &body body)
  `(call-with-repeat ,times (lambda () ,@body)))
(let ((x "hi"))
  (repeat 3 (print x)))

;; compile time computing
use to reduce execution calculations and for developer errors at compile time
defun*

;; lists vs AST
CL macros manipulates lists of symbols

;; symbol-macro

;; read time evaluation with #.

;; macro-step
#+end_src

** CLOS
;; pretty printing
;; defclass
;; custom constructors
;; initialize-instance
;; multiple inheritance
;; defgeneric vs defmethod
;; class allocation
** quoting data
** logic
** control
* Shelter Concepts

- Shelter's idea of working directory is completely independent of the rest of the program.
- In fact shelter is designed to be independent of the rest of the image
- its purpose is to be a shelter used to explore files at runtime without making any impact on the running program

* Shelter Operations
** Implemented

- builtins that wont be overridden
  - sort
  - time
  - find

1. pwd
2. ls
3. cd
4. which
5. cat
6. head
7. tail

** Not implemented

Listed in priority order from partially completed to planned.

1. rm
2. mv
3. cp
4. touch
5. rmdir
6. mkdir
7. echo
8. chown
9. chmod
10. grep (file grep, needs to map ppcre string matching for composability)
11. wc
12. uniq
13. whoami
14. date
15. uname

I would love to pilfer the best parts of nushell as well

** shelter custom

- *default-pathname-initialized*
  - root pathname for point of initization
  - immutable
- *default-pathname-project*
  - root pathname for project
  - mutable

- find-dir
  - fuzzy find directory
  - details below

- on-start
  - automatically invoked
  - sets pathname for *default-pathname-initialized*
  - sets pathname for *default-pathname-project*
  - updates all distributions
  - will have clerk jobs

- on-project
  - user invokes
  - sets pathname for *default-pathname-project*
  - will have clerk jobs

- p
  - minimal keystoke maximal utility print parser
  - not implementd

- help
  - interactive help menu
  - not implemented

* Interop
** Cmd
Calls to command line, protected and various return types
https://github.com/ruricolist/cmd

#+begin_src lisp
                                          ; Loading
  (ql:quickload :cmd)
  (use-package :cmd)

                                          ; Usage
  ($cmd "ls")
  ($sh "cd ~; ls")
  ($sh "pwd")
  ($cmd "echo a b \
                    c \
                    d")

  ($cmd "echo 'hello world' >> text.txt")
  ($cmd "echo 'hello world' > text.txt")

  (defun call-cmd (arg arg1)
    ($cmd (format nil "echo hello:
                                   ~A
                                   ~A" arg arg1)))
  (call-cmd "Lamb" "Duh")

                                          ; &&& return types
  (cmd "cmd")
  ($cmd "cmd")
  ($sh "cmd")

#+end_src

** py4cl2

Python interop
https://github.com/digikar99/py4cl2

#+begin_src lisp

  (ql:quickload :py4cl2)
  (use-package :py4cl2)

                                          ; first time manually initialize
  ;; (py4cl2:initialize)
  ;; ;; python3, ret, ret, ret
  ;; (print py4cl2:*config*)
  ;; (setf (config-var pycmd) "python3") ; set one field

                                          ; test if pycmd finds python on path
  (py4cl2:pyversion-info)    ; fails if python command is not resolved

                                          ; test usage
  (py4cl2:pyexec "print(\"hello\")")    ; => hello
  (py4cl2:defpymodule "math")
  (py4cl2:pyeval "math.pi")             ; 3.1415...
  (py4cl2:defpymodule "numpy" nil :lisp-package "NP")
  (np:floor 4.2)                        ; => 4.0
  (py4cl2:pyeval "[i**2 for i in range(5)]")

                                          ; import and environment
  (defpymodule "os" nil :lisp-package "OS")
  (defpymodule "sys" nil :lisp-package "SYS")
  (defpymodule "pprint" nil :lisp-package "PPRINT")
  (pyexec "sys.path.append('/home/user/code/dircontainingscript')")
  (pyexec "sys.path.append('/home/user/.local/lib/python3.10/site-packages')")
  (pyexec "sys.path.append('/home/user/.guix-profile/lib/python3.10/site-packages')")
  ;; check python path contains target and path to imported modules
  (pyexec "pprint.pprint(sys.path)")
  (os:getcwd)
  (os:listdir)

                                          ; test setup
  ;; NOTE: files on path cannot have '-' in them or defpymodule fails, with NIL!!!
  ;; NOTE: If the file has a compilation error, then import will return NIL!!!
  ;; NOTE: unresolved module import is one such silent failure mode.
  ;; create pytest.py on python path which contains the following.
  ;; ======================================
  ;; def test():
  ;;     print("test sucessfull")

  ;; def argument(a):
  ;;     print(a)

  ;; def math(x):
  ;;   y = x * x
  ;;   return y
  ;; ======================================

                                          ; test import script on path
  (defpymodule "pytest" nil :lisp-package "PYTEST")
  (pytest:test)
  (pytest:argument :a "hello")
  (pytest:argument :a 42)
  (pytest:math :x 9)
  ;; must stop and restart to re import with changes

                                          ; stop
  (py4cl2:pystop)
  (py4cl2:python-alive-p)

#+end_src

** Clesh
https://github.com/Neronus/clesh
clesh is included here mostly to show off how
flexible lisp can be, this is almost unthinkable in other languages, yet it is
transparently available without core language changes.

I recommend using cmd over clesh for permanent work, but for experimental, fast
tasks, scripts etc this mixed inlining is very handy indeed. cmd is more
controlable and disciplined and better suited for wrapping calls for serious
use.

#+begin_src lisp
                                          ; load
  (ql:quickload :clesh)
  (use-package :named-readtables)
  (in-readtable clesh:syntax)

                                          ; usage
  ;; repl out
  !ls
  !echo ?(+ 2 3) foo 5 bar

  ;;messages out
  [echo one two three] ;call bash command
  [echo one ?(+ 1 1) three] ;call lisp command in bash command
  (princ [echo foo]) ;call bash command in lisp command

  (defparameter *val* 42)
  [echo one ?*val* three] ;sub lisp var in bash arg
  [echo one ?(princ *val*) three] ;sub lisp command in bash arg

  ;; break bash commands
  [echo one \
  two \
  three]

  (princ [echo one \
         ?*val* \
         three]) ;sub lisp var in bash arg

  (princ [echo one \
         ?(+ *val* *val*) \
         three]) ;sub lisp command in bash arg

  ;; within a function
  (defun call-clesh (arg arg1)
    [echo \
    Hello: \
    ?arg \
    "FOO" ?arg1])
  (call-clesh "Lamb" "Duh")
#+end_src

** Scripting with CL
*** guides

-  sly adapted as shell https://web.archive.org/web/20210730202847/https://ambrevar.xyz/lisp-repl-shell/index.html
- https://simonsafar.com/2021/lisp_scripting/
- https://fare.livejournal.com/184127.html
- https://atomized.org/blog/2020/07/06/common-lisp-in-practice/
- shell wrapper https://www.cliki.net/CL-Launch

*** command line args

unix-opts
https://github.com/libre-man/unix-opts

The UNIX command line args can be read from the variable =sb-ext:*posix-argv*=

*** export binaries

(uiop/image: &&&)

** &&& clojure R etc
TODO Unified example of library interop, and program interop to minimal program with one argument for each lang
* Select Systems

Some examples are provided.

** strings

str
https://github.com/vindarel/cl-str

(str:split " " "hello world") ; => ("hello" "world")
(str:replace-all old new string)
(str:lines &&&)

regex
https://edicl.github.io/cl-ppcre/

time
https://local-time.common-lisp.dev/

** testing
https://github.com/lmj/1am
https://github.com/AccelerationNet/lisp-unit2
** GUI

clog common lisp omnificient gui
https://rabbibotton.github.io/clog/cltt.pdf

** logging

https://github.com/7max/log4cl

** iteration
*** built in

#+begin_src lisp
  ;;dotimes
  (dotimes (n 3)
    (print n))

  ;;dolist
  (dolist (i '(1 2 3))
    (print i))

  ;;mapcar
  (mapcar #'print '(1 2 3))

  ;; There is also the built in loop macro, its syntax is powerful, but non idiomatic
#+end_src

*** iterate

https://iterate.common-lisp.dev

#+begin_src lisp
  (ql:quickload :iterate)
  (use-package :iterate)

  (iterate:display-iterate-clauses)

  (defparameter *my-vector* #(1.1 2.2 3.3 4.4))
  (defparameter *my-list* '(1 2 3 4))

  (defparameter *my-hashtable* (make-hash-table))
  (setf (gethash 'a *my-hashtable*) 10)
  (setf (gethash 'b *my-hashtable*) 20)
  (setf (gethash 'c *my-hashtable*) 30)

  ;; hashtables
  (iter (for (k v) in-hashtable *my-hashtable*)
    (collect (cons k v)))

  ;; List iteration
  (iter (for i in *my-list*)
    (collect i))

  ;; Vector iteration
  (iter (for v in-vector *my-vector*)
    (collect v))

  ;; ranges
  (iter (for i from 1 to 10)
    (collect i))
  (for i upfrom 0)
  (for i from 5)
  (for i downfrom 0)
  (for i from  1 to 10)
  (for i from 1 below 10)
  (for i from 1 to 10 by 2)
  (for i from 10 downto 1)

  ;; Nested iterations:
  (iter outer (for i from 1 to 3)
    (iter (for j from 1 to 3)
      (in outer (collect (list i j)))))

  ;; Conditional collection:
  (iter (for i from 1 to 10)
    (when (evenp i)
      (collect i)))

  ;; Summing:
  (iter (for i in '(1 2 3 4 5))
    (sum i))

  ;; Finding maximum:
  (iter (for i in '(3 7 2 9 1))
    (maximize i))

  ;; String iteration:
  (iter (for char in-string "Hello")
    (collect (char-upcase char)))

  ;; Iterating with multiple variables:
  (iter (for i from 1 to 5)
    (for j from 10 downto 6)
    (collect (list i j)))

  (iter (for i from 1 to 5)
    (for j from 1 to i)
    (collect (list i j))) &&&

  ;; Early termination:
  (iter (for i from 1)
    (while (< i 5))
    (collect i))

                                            ; Simple iteration over a range:
    (iter (for i from 1 to 10)
      (sum i))

                                            ; Simple iteration over a list:
    (iter (for x in '(1 2 3 4 5))
      (sum x))

                                            ; Iterating over a range of numbers:
    (iter (for i from 1 to 5)
      (collect (* i i)))

    (iter (for i from 1 to 5)
      (sum (* i i)))

                                            ; Iterating over a hash table:
    (let ((ht (make-hash-table)))
      (setf (gethash 'a ht) 1
            (gethash 'b ht) 2
            (gethash 'c ht) 3)
      (iterate (for (k v) in-hashtable ht)
        (collect (list k v))))
                                            ; => ((C 3) (B 2) (A 1))

                                            ; Nested iteration:
    (iter (for i from 1 to 3)
      (collect (iterate (for j from 1 to i)
                 (collect j))))
                                            ; => ((1) (1 2) (1 2 3))
#+end_src

** event scheduling
*** shelter

&&& Initialization functions custom to shelter
- on-start
- on-project

*** clerk

#+begin_src lisp
  (ql:quickload :clerk)
  (use-package :clerk)

  ;; Make sure your jobs are loaded before executing (clerk:start)
  ;; &&&verify
  (clerk:job "Say 'Hello' often" every 5.seconds (print "Hello"))
  (clerk:start)
  (clerk:stop)

  (defun bark ()
    (print "Bark!"))

  (clerk:job "The dog barks" every 7.seconds (bark))
  (clerk:start)
  (clerk:stop)

  ;; The jobs reside inside clerk:*jobs*,
  (dolist (j clerk:*jobs*)
    (print j))
  ;; list of all scheduled and running jobs.
  (clerk:calendar)

  (clerk:empty-jobs-queue)
  (clerk:calendar)

  ;; all examples above are continuous jobs, set with every
  ;; one time jobs are also available
  ;; use in  or after to set one time jobs
  (clerk:job "Say 'Hello' often" every 5.seconds (print "Hello"))
  (clerk:start)
  (clerk:job "Bark once" in 15.seconds (bark))
  (clerk:calendar)
  (clerk:stop)
  (clerk:empty-jobs-queue)

  ;;programmatic setup
  (defparameter *query-interval* 30)
  (clerk:job-function (format nil "Task set for every: ~A seconds" *query-interval*)
                      'every `(,*query-interval* seconds)
                      #'bark) ; requires a function symbol or lambda
#+end_src

Intervals

interval-type is one of the following (plural is equivalent, ie minute = minutes):
second minute hour day week month year
=<+ve integer>.<interval>=

or Days of the week
if you type the day of the week, clerk will calculate when it is and add an event to the queue.
=(job "Weekly report" every monday (create-report))=

** database

mito
https://github.com/fukamachi/mito

** math

in hyperspec as numbers
https://novaspec.org/cl/12_1_Number_Concepts

** data structures

reading
- https://blog.djhaskin.com/blog/common-data-structures-in-common-lisp/

access uniformity
https://github.com/AccelerationNet/access/

fset
https://github.com/slburson/fset

gmap
https://github.com/slburson/misc-extensions

listopia
https://github.com/Dimercel/listopia

*** a and p lists

&&&

*** hashtables

#+begin_src lisp
                                          ; Creating and using a simple hashtable:
  (defvar *fruit-prices* (make-hash-table :test #'equal))

  (setf (gethash "apple" *fruit-prices*) 0.50)
  (setf (gethash "banana" *fruit-prices*) 0.75)

  (format t "An apple costs $~A~%" (gethash "apple" *fruit-prices*))

                                          ; Using gethash with a default value:
  (defvar *user-scores* (make-hash-table))

  (setf (gethash "Alice" *user-scores*) 100)

  (format t "Bob's score: ~A~%" (gethash "Bob" *user-scores* 0))

                                          ; Iterating over a hashtable:
  (defvar *capitals* (make-hash-table :test #'equal))
  (setf (gethash "France" *capitals*) "Paris"
        (gethash "Japan" *capitals*) "Tokyo")

  (maphash #'(lambda (country capital)
               (format t "The capital of ~A is ~A~%" country capital))
           ,*capitals*)

                                          ; Removing an entry and checking the count:
  (defvar *inventory* (make-hash-table))
  (setf (gethash 'book *inventory*) 5
        (gethash 'pen *inventory*) 10)

  (remhash 'book *inventory*)
  (format t "Items in inventory: ~A~%" (hash-table-count *inventory*))
#+end_src

** data formats IO

json
https://github.com/Zulu-Inuoe/jzon/

csv
https://github.com/AccelerationNet/cl-csv

xlsx
https://github.com/defunkydrummer/lisp-xl
on github &&& install notes

** distribution

*** quicklisp

https://www.quicklisp.org/beta/
https://common-lisp-libraries.readthedocs.io/quicklisp/

- quicklisp links to docs https://quickref.common-lisp.net/index-per-library.html
- quicklisp catalogue https://www.quicklisp.org/beta/UNOFFICIAL/docs/
- quicklisp search https://quickdocs.org/

#+begin_src lisp

  ;; check installed dists
  (ql-dist:all-dists)

  ;; &&&note on
  (quicklisp:update-all-dists)

  ;; &&& how to uninstal dists
  ;; &&&reinstall dists
#+end_src

*** ultralisp
https://ultralisp.org/
*** ocicl
https://github.com/ocicl/ocicl
*** asdf
https://asdf.common-lisp.dev/
* Software Sources

ocicl libraries list
https://raw.githubusercontent.com/ocicl/request-system-additions-here/main/all-ocicl-systems.txt

quick lisp libraries list
https://quickref.common-lisp.net/index-per-library.html

ultralisp libraries list
https://dist.ultralisp.org/ gets you the latest distinfo as a file
https://dist.ultralisp.org/ultralisp/20260819025001/systems.txt gets the list of packages as a file

common lisp hosting
https://common-lisp.net/
https://common-lisp.net/phub

* Resources
** essential links

use the cookbook
https://lispcookbook.github.io/cl-cookbook/

hyperspec
https://www.lispworks.com/documentation/HyperSpec/Front/

novaspec
https://novaspec.org/cl/

minispec
https://lamberta.github.io/minispec/

** common common lisp functions
- &&& extract outline of minispec
** important systems
*** uiop
- manual https://asdf.common-lisp.dev/uiop.html
- &&& list of functions available
*** asdf
- defacto docs https://asdf.common-lisp.dev/
- manual https://www.sbcl.org/asdf/
- &&& list of functions available
*** alexandria
- defacto docs https://alexandria.common-lisp.dev/draft/alexandria.html
- manual https://alexandria.common-lisp.dev/draft/alexandria.html
- &&& list of functions available
*** serapeum
- github https://github.com/ruricolist/serapeum
- manual https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md
- &&& list of functions available

** lists of packages

- awesome common lisp list https://github.com/CodyReichert/awesome-cl
- common lisp wiki, almost every CL package https://www.cliki.net/
- another lisp https://common-lisp.net/libraries
- defacto libraries docs page https://common-lisp-libraries.readthedocs.io/
  - asdf - Build System
  - alexandria - Commonly Used Utilities
  - bordeaux-threads - Threading
  - cl-ppcre - Regular Expressions
  - cl-who - DSL for Markup
  - fiveam - Regression Testing Framework
  - hunchentoot - Web Server
  - iterate - Psuedocodic Iteration
  - local-time - Date and Time Manipulation
  - postmodern - PostgreSQL programming interace
  - quicklisp - Library Manager
  - usocket - Universal Socket Library
  - utilities - A collection of utility libraries
  - numcl - Lispy clone of numpy
  - unix-opts - cmd line argument parser

** programming guides

- syntax crash course https://learnxinyminutes.com/docs/common-lisp/
- lisp crash course https://cs.gmu.edu/~sean/lisp/LispTutorial.html
- great teacher https://stevelosh.com/blog/2018/08/a-road-to-common-lisp/
- learn lisp the hard way https://llthw.common-lisp.dev/
- another terser cookbook https://cl-cookbook.sourceforge.net/index.html
- common lisp by example http://csci.viu.ca/~wesselsd/courses/csci330/code/sbcl-lisp/index.html
- successful lisp book https://dept-info.labri.fr/~strandh/Teaching/MTP/Common/David-Lamkins/contents.html

** learn by watching

- https://www.youtube.com/@the-lisper/videos
- https://www.youtube.com/watch?v=0RQYa2XJBKU
- https://www.youtube.com/@philipbohun740/videos
- https://www.youtube.com/watch?v=rmUTW5QWhhM&list=PL2VAYZE_4wRJi_vgpjsH75kMhN4KsuzR_&index=2

** reference

- sbcl man http://www.sbcl.org/manual
- technical syntax quick reference http://clqr.boundp.org/clqr-a4-consec.pdf
- documentation redirect service http://l1sp.org/html/
- googles lisp style guide https://google.github.io/styleguide/lispguide.xml
- style guide http://mumble.net/~campbell/scheme/style.txt

** heavy hitters

some seriously potent programmers

- lisp-maintainers https://github.com/vindarel/lisp-maintainers
- sharp lispers https://github.com/sharplispers
- shinmera https://codeberg.org/shinmera/
- fukamachi https://github.com/fukamachi
- vindarel https://github.com/vindarel/
- robert smith https://github.com/stylewarning
- ruricolist https://github.com/ruricolist

** reading

- advanced functional programming https://www2.cs.sfu.ca/CourseCentral/310/pwfong/Lisp/2/tutorial2.html
- page 13 explained in pythoooon https://michaelnielsen.org/ddi/lisp-as-the-maxwells-equations-of-software/
- page 13 in modern scheme https://www.gnu.org/software/mes/manual/html_node/LISP-as-Maxwell_0027s-Equations-of-Software.html
- LOL book https://letoverlambda.com/index.cl/toc
- blog and lisp bibliography https://simondobson.org/writing/
- lisp nn from primitives https://woodrush.github.io/blog/posts/2022-01-16-neural-networks-in-pure-lisp.html
- interactive programming implications https://www.n16f.net/blog/interactive-common-lisp-development/

** citations

- https://www.math.fau.de/wp-content/uploads/2020/09/Preprint-2002-40-scan.pdf
- &&& bring other lisp citations here!

* CLEAN
Common Lisp Environment for Experiment and Analysis

All advanced data science ML and modelling goes here
If shelter is the living room clean is the laboratory

I want an operating system for data science,
deployable pipelines and experiment tracking is the goal

declarative file system state
https://github.com/Virtual-Insurance-Products/cl-sysop

Depot
file system protocol browse read write with locks and ACID safety
https://shinmera.github.io/depot/

clml machine learning
https://github.com/mmaul/clml

cl-ana
data frames stats and dependency oriented programming
https://github.com/ghollisjr/cl-ana/wiki

memoization
https://github.com/AccelerationNet/function-cache

ML
https://github.com/melisgl/mgl

nvidia interop
https://github.com/takagi/cl-cuda

lispstat - linear algebra - stats - plot
https://lisp-stat.dev/
#+begin_src lisp
                                          ; RE bug on loading in guix
                                          ; Cffi path Ref: https://lists.gnu.org/archive/html/bug-guix/2020-01/msg00133.html
(ql:quickload :lisp-stat) ; stats

                                          ; usage&&&
#+end_src

deep learning matrices matrices
https://github.com/hikettei/cl-waffe2

syntax modification useful for data pipelines
https://quickref.common-lisp.net/arrows.html

numcl, numpy clone
https://numcl.github.io/numcl/
#+begin_src lisp
                                          ; Creating and manipulating arrays:
  (numcl:array '(1 2 3 4 5))  ; Create a 1D array
  (numcl:zeros '(3 3))        ; Create a 3x3 array of zeros
  (numcl:aref my-array 1 2)   ; Access element at row 1, column 2

                                          ; Basic operations:
  (numcl:+ (numcl:array '(1 2 3)) (numcl:array '(4 5 6)))  ; Element-wise addition
  (numcl:* (numcl:array '(1 2 3)) 2)                       ; Scalar multiplication

                                          ; Mathematical functions:
  (numcl:sin (numcl:array '(0 (/ pi 2) pi)))  ; Element-wise sine
  (numcl:exp (numcl:array '(0 1 2)))          ; Element-wise exponential

                                          ; Linear algebra:
  (numcl:matmul matrix1 matrix2)  ; Matrix multiplication
  (numcl:transpose my-matrix)     ; Matrix transposition
#+end_src

&&& gnu scientific library for cl

System info
https://github.com/Shinmera/machine-state/

** lparallel

#+begin_src lisp
                                          ; lparallel startup
  (ql:quickload :lparallel)
  (use-package :lparallel)
  (setf lparallel:*kernel* (lparallel:make-kernel 8)) ;set worker threads

                                          ; env setup for examples
  (defun gt-five (x)
    (if (> x 5)
        x))

  (defun lt-five (x)
    (if (< x 5)
        x))

  (defparameter *mylist* '(0 1 2 3 4 5 6 7 8 9 10) )

                                          ; usage
  (pmap 'list (lambda (x) (* x x)) '(1 2 3 4))
  (preduce #'+ #(1 2 3 4 5))

  (premove '5 '(1 2 3 4 5 6 7 8 9 0))

  (premove-if (lambda (x) (> x 5)) '(0 1 2 3 4 5 6 7 8 9 10))
  (premove-if #'gt-five '(0 1 2 3 4 5 6 7 8 9 10))
  (premove-if #'gt-five *mylist*)

  (premove-if-not #'gt-five *mylist*)
  (premove-if #'gt-five *mylist*)
  (premove-if #'lt-five *mylist*)
  (premove-if-not #'lt-five *mylist*)

  (defun my-filter (predicate list)
    (reduce 'nreconc
            (lparallel:preduce-partial (lambda (acc x)
                                         (if (funcall predicate x)
                                             acc
                                             (cons x acc)))
                                       list
                                       :initial-value nil)
            :initial-value nil
            :from-end t))

  (my-filter #'gt-five *mylist*)
  #+end_src

** generators

gtwiwtg - generators the way I want them generated
https://github.com/d3v3l0/gtwiwtg
https://cicadas.surf/cgit/colin/gtwiwtg.git/about/
clear and modernized and documented


series
https://github.com/rtoy/cl-series
A high quality high perf, classic lib but docs and examples are hard to find

** types

coalton
https://github.com/coalton-lang/coalton/
