* SHELTER

A "Shell" providing familiar linux Command Line Interface in the Common Lisp REPL
An introduction to Common Lisp by common patterns

The initial interface to a computer is the terminal and shell: poke filesystem, issue command, minimal structure, maximal flexibility.

The vast majority of projects begin in shell:  minimal grand plans, maximal inquiry,
then some abomination of bash or poor perf python grows around that beginning (why not both!).

The aim of shelter is to make that exploratory phase a path which flows directly into CL.
The goal is to make evolution from early inquiry to a fully fledged high perf program easy.

Common lisp provides an interactive REPL, which has comparable attributes to a terminal,
and the majority of shell like functions exist, although they may have arcane names, and be found spread across an expedition of packages.

In shelter, basic shell commands should feel native.
Anybody with programming/bash experience should be immediately at home on the REPL.

The educational parts of Shelter are not meant to be a comprehensive introduction, or the ultimate library.
These are my opinionated selections and frequently used examples that get me productive and learning through use.
Though I do enjoy the sprawling options and obscure tools that common lisp provides,
a focused on-boarding would have helped immensely, this is the practical onboarding I would have wanted to have.

This is a Work In Progress

Initially shell functions can be simple wrappers,
the goal is to eventually have them all in portable common lisp,
and have each doc-string describe the canonical CL approach.

  - Purpose
    - Shelter answers the question: what 20%  does 80% of the work?
      - concepts
      - operations
      - systems and packages
    - Shelter serves as an on ramp to common lisp concepts
      - The setup and discovery of common lisp is an obstacle due to its history and complexity.
      - Getting past this steep initial learning curve to the good stuff of Common Lisp should be made gradually.
      - Assuming that users interested in common lisp have prior linux and bash knowledge, is the key
    - Shelter should ease daily tasks, such that the REPL becomes easier and more useful than bash shell
      - So that projects can begin in the REPL and then grow into their potential

Note: let &&& be "right here completion needed"

* Startup

Nice intro
https://lisp-lang.org/

Mini spec - most used topics and examples
https://lamberta.github.io/minispec/

Questions and discovery
https://lisp-docs.github.io/

** SBCL

steel bank common lisp
https://www.sbcl.org/

install from command line
#+begin_src bash
sudo apt-get install sbcl
#+end_src

** quicklisp

https://www.quicklisp.org/beta/

install from command line
#+begin_src bash
curl -o /tmp/quick.lisp http://beta.quicklisp.org/quicklisp.lisp
sbcl --no-sysinit --no-userinit --load /tmp/quick.lisp \
       --eval '(quicklisp-quickstart:install :path "~/quicklisp")' \
       --eval '(ql:add-to-init-file)' \
       --quit
#+end_src

** ultralisp

https://ultralisp.org/

install from command line
#+begin_src bash
sbcl --eval '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)' --quit
#+end_src

** ocicl

install from command line
#+begin_src bash
# install ocicl binary to &&&
temp="~/ocicl-temp"
mkdir -p ${temp} && cd ${temp}
git clone https://github.com/ocicl/ocicl.git
cd ocicl
sbcl --load setup.lisp
cd ~ && rm -rf ${temp}

# modify ~/.sbclrc
ocicl setup

# create a "top level" ocicl dir in home
cd ~
sbcl --eval '(asdf:load-system :str)' --quit
#+end_src

** shelter

install from command line
#+begin_src bash
  git clone https://github.com/metarepl/shelter ~/common-lisp/shelter
#+end_src

** spacemacs

install from command line
  #+begin_src bash
    # install emacs
    apt install emacs

    # clone spacemacs
    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
    cd ~/.emacs.d
    git checkout develop

    #copy my dotfile
    temp="~/dotfile"
    mkdir -p ${temp} && cd ${temp}
    git clone https://github.com/metarepl/uncommon-dotfiles.git ~/uncommon-dotfiles
    cd ~/uncommon-dotfiles
    cp spacemacs/.spacemacs ~/.spacemacs
    cd ~ && rm -rf ${temp}

    # first start will bootstrap spacemacs
    emacs
    # wait for compilation

    # quit
    SPC q q
#+end_src

- basic spacemacs dotfile guide
  - ~/.spacemacs configures spacemacs and can be modified to suit your needs
  - search for "dotspacemacs-configuration-layers"
  - this is a list of "layers" spacemacs provides
  - for more options see https://www.spacemacs.org/ click "layers list"

** use shelter

- in bash open spacemacs
  - emacs
- open scratch buffer
  - SPC b s
- actvate lisp mode
  - SPC SPC lisp-mode
- activate REPL
  - , '
- at the prompt evaluate commands
  - (print "hello lisp") RET

evaluate in the REPL
#+begin_src lisp
  ;; preferred with ocicl
  (asdf:load-system :shelter)
#+end_src

evaluate in the REPL
#+begin_src lisp
  (ls)
  (cd)
  (pwd)
  ;; &&& etc
  ;; (documentation 'pwd 'function)
#+end_src

* project structure

- A SYSTEM is a collection of packages,
- A PACKAGE is a collection of symbols,
- A SYMBOL can be a variable or a function,
- Symbols are exported by the package declaration.
- Packages are organized by the system declaration

Common lisp gave these names to this nested structure of code and project organization long long ago when the earth was green.
Unfortunately, incumbent language designers chose conflicting terminology.
Restated in more familiar terms: A package (in lisp: system) is a collection of namespaces.
A namespace (in lisp: package) is a collection of exports.

The system declaration organizes packages, but it also declares dependencies, organizes source code and the build order.
The ASDF system declaration is used to by the build system.
This is like make, but more powerful more flexible and far easier to use.
By beginning with ASDF systems, the whole dependency tree of systems can be compiled into the image,
with one command:

(asdf:load-system :that-was-easy)

** Systems

- Lisp systems
  - system definition is declarative
  - contains meta data of the project similar to debian packages
  - possible to create multiple systems per asd file

- it is the easy default for the asd file to match the dir, but not absolutely necessary

- my-project (dir)
  - my-project.asd (file)

#+begin_src lisp
  ;;an example my-project.asd file
  (defsystem :my-project
    :depends-on (:alexandria :str)
    ;; components in flat file system
    ;; - my-project.asd
    ;; - my-project.lisp
    ;; - README.org
    :serial t
    :components ((:file "my-project") ; a .lisp file
                 (:static-file "README.org"))
    ;; components in hierarchical file system
    ;; my-project.asd
    ;; - src
    ;;   - utils.lisp
    ;;   - my-project.lisp
    ;;   - config.lisp
    ;; - test
    ;;   - tests.lisp
    :serial t
    :components ((:module "src"
                  :components ((:file "utils")
                               (:file "my-project")
                               (:file "config")))
                 (:module "test"
                  :components tests)))
  ;; defsystem is capable of complex loading order dependencies

  ;; an example my-project.lisp file
  (in-package :cl-user)
  (defpackage #:my-package
    (:use :cl)
    (:export :my-function))
  (in-package :my-package)
  (defun my-function ()
    "an exported function"
    (print "hello world"))
#+end_src

Interactive loading
  clone a project to local, eg str
  cli nav to find system definintion, eg str.asd
  start a lisp
  $ sbcl
  CL-USER>
#+begin_src lisp
  ;;load system definition
  (asdf:load-asd "str.asd") ; use exact path

  ;; load system
  (asdf:load-system "&&&") ; will not load dependencies
  (asdf:system-depends-on (asdf:find-system "str")) ; list of dependencies

  (ql:quickload :str) ; recursively loads dependencies
  (in-package :str) ; enter the package to use internal functions

  ;; in emacs open str.asd file
  C-c C-k to compile and load

  (ql:quickload :str)
  (in-package ::str) or C-c ~
#+end_src

** Packages and imports

  lisp packages
  a container to group symbols together
    a symbol is a basic type denoting a funciton or a variable or other things

  a package is a first class object
  used as namespaces
  possible to create multiple packages per system/project

  initially the repl places the user in the cl-user package
  CL-USER> *package*
  cl-user contains basic functions variables and macros, defun etc

#+begin_src lisp
  (in-package :cl-user) ; make cl-user package available now
  (defpackage :my-package
    (:use :cl) ; :cl bring cl-user symbols into my-package
    (:export :*exported-symbol*))
  (in-package :my-package)

  ;; (export '*exported-symbol*) ;export in place or use :export in definition
  (defparameter *exported-symbol* 'hello)


  ;; check available symbols in a package
  (do-external-symbols (sym :cl)
    (print sym)) ; show current symbols ~1000

  (do-external-symbols (sym :my-package)
    (print sym)) ; our one symbol
#+end_src

Package symbols interaction details
#+begin_src lisp

                                          ; imports
  (ql:quickload :cmd)
  (ql:quickload :str)
  (ql:quickload :file-finder)
  (ql:quickload :com.inuoe.jzon)
                                          ; package declaration
  (defpackage :my-package
                                          ; whole package import
    (:use :cl :str :cmd :file-finder)
                                          ; shadowing, declares dominant function
    (:shadowing-import-from :cmd :current-directory)
                                          ; specific function import to this namespace
    (:import-from :uiop
     :subdirectories :directory-files :getcwd)
                                          ; rename package and or function
    (:local-nicknames (:jzon :com.inuoe.jzon))
                                          ; export functions and params to the shelter: name space
    (:export
     :my-function
     :*my-parameter*
     ))
                                          ; enter package
  (in-package :my-package) ; Also enter this in the REPL
  ;; to leave (in-package :cl-user), :my-package maintains state

                                          ; load local file
  (load (merge-pathnames #P"path/to/my-file.lisp" (uiop:getcwd)))
  #+end_src

** naming convention

- naming of systems and packages has very few constraints, these are the patterns I often use.

*** repo name

- github.com/metarepl/cool-proj
  - metarepl.category-specifier.cool-proj.asd
  - package.lisp
  - src/cool-proj.lisp

*** system name

(asdf:defsystem "metarepl.category-specifier.cool-proj" ;; must match the asd file name
  :depends-on (:other-asdf-system)
  :serial t
  :components (
               (:file "package")
               (:module "src"
                :components (
                             (:file "cool-proj")
                             ))))
*** package name

(defpackage #:cool-proj
  (:use #:cl
        #:uiop)
  (:export #:*my-symbol*
           #:my-function))
* Lisp Concepts
** Intro
In the core of lisp the meta circular evaluator was discovered by John Mcarthy;
from system primitives lisp develops a self evaluator for the language, and then builds out to
create the language. The implication of this is that lisp is built ON lisp, and
when you work you will be working ON the language. You are outside a set of
tools building and refining tools to move up and out. This is profoundly
different from working in a language. For other programming scenarios we work
within the constraints of the language. We work on one program, in a language
which is in turn inside the operating system.

When we work on lisp we are inside the image. Outside the image is the OS handling
multi tasking. The running lisp image is best though of as like an OS, not
quite, but almost. Inside the image is a place for programs, programs, we are
not restricted to a single program. This is why the order of function
definition doesn't matter, all the functions are compiled into the image,
multiple programs in one document can exist within the image at one time. The
running image for us has an interactive repl, functions, programs, scheduled
tasks, individual functions can be hot recompiled while the image
runs. Essentially, we have at our disposal a language we can modify to fit any
domain specific purpose, within a live system that we can interactively design to
accomplish a task or behaviour, including running multiple programs
simultaneously. When the goal is reached, that image can be exported as is, for
distribution. Yes that could be a simple script, an app, or an OS.

Freedom, sometimes means being lost. many operations we take for granted as
necessarily being bound together are orthogonal in CL.
- import is independent of use
- chdir is independent of *default-directory-defaults*
- in-package for the code is indpendent of in-package for the REPL
- &&&
Many granular steps are available and required to precisely specify the system,
none of this is particularly verbose, but it does require a change of details to
attend to. If something is not working as expected, I check what actions I have
assumed are accomplished by some explicit command.
** Image
The image is the program, running in memory.
It is live in that parts of the image can be dynamically modified.
An image can contain multiple systems, and packages.
** shelter custom

- *default-pathname-initialized*
  - root pathname for point of initization
  - immutable
- *default-pathname-project*
  - root pathname for project
  - mutable

- find-dir
  - fuzzy find directory
  - details below

- on-start
  - automatically invoked
  - sets pathname for *default-pathname-initialized*
  - sets pathname for *default-pathname-project*
  - updates all distributions
  - will have clerk jobs

- on-project
  - user invokes
  - sets pathname for *default-pathname-project*
  - will have clerk jobs

- p
  - minimal keystoke maximal utility print parser
  - not implementd

- help
  - interactive help menu
  - not implemented

** REPL and error and messages
- editor function
  - https://lispcookbook.github.io/cl-cookbook/emacs-ide.html

- interact with the repl
  - &&&
- move around in error message
  - &&&
- Observe objects:
  - (inspect "string")
  - (describe "string")
  - (apropos "string")
  - (documentation "string")
- Evaluate single form in place: =,-e-c=

** find-dir

find-dir takes a list of paths and fuzzy filters directories, if depth is set it descends into directory tree,can be sequentially applied to its own output.

arg : default action : description
root : '(#P\"/\") : a list with paths or a path in #P or string form
depth : 0 : an integer for retrieval depth below roots, default 0 goes no deeper for filtering root list
keep : all : space delimited words to separately(additive to set) fuzzy filter in
drop : none : space delimited words to separately(additive to set) fuzzy filter out, applied after keep
report : none : set true for reporting on processing, big ass reports if depth is large
n-test : off : integer for required num of paths in output list, error and report if not "

#+begin_src lisp

  (find-dir :keep "lib opt" :drop "etc lib gnu" :depth 2)
  (find-dir :report t :keep "lib opt" :drop "etc lib gnu" :depth 2)
  (find-dir :n-test 6 :depth 3 :keep "opt" :drop "gnu"  )
  (find-dir :drop "chrome"
            :root (find-dir :depth 2
                            :keep "opt"
                            :drop "gnu"))


#+end_src

** finder
https://github.com/lisp-maintainers/file-finder/

convenience wrapper
=(finder (name~ "string")) => #F"file_object.type"=
granular control
=(finder* :predicates (name~ "string" ) :root <string | #P> ) => #F"file_object.type"=


Finder predicates
path
- =path~= matches when one of the path elements is contained in the file path.
- =every-path~= same checks on the file path, but uses a logical and.
- =path$= matches when one of the path suffixes matches the file path.

file name
- =name== matches when one of the names matches the file name (case sensitive).
  - full file name
- =iname== matches when one of the names matches the file name (case insensitive).
- =name~= matches when one of the names is contained in the file basename (and not the whole path), case sensitive.
  - partial name
- =iname~= matches when one of the names is contained in the file, case insensitive.
- =every-name~= same checks on the file basename, but uses a logical and.

extension
- =extension== matches file extensions
  -  full exact

recur predicates
- =depth<= matches when the argument file is in a subdirectory of ROOT less deep than LEVEL.
- =hidden?= return t if this is a hidden file

#+begin_src lisp
  (ql:quickload :file-finder)
  (use-package :file-finder)



  ;; basic
  (file-finder:finder* :root "/home/user/Downloads")
  (file-finder:finder* :predicates (file-finder:extension= "txt")
                       :root "/home/user/Downloads")
  ;; recur predicates
  (file-finder:finder* :predicates (file-finder:extension= "txt")
                       :recur-predicates (complement #'file-finder:hidden?)
                       :root "/home/user/Downloads")

  ;; predicates AND
  (finder* :predicates (list (name~ "test")
                             (complement (path~ "exclude"))
                             (extension= "txt"))
           :root "/home/user/Downloads")

  ;; call with find-dir for root
  (file-finder:finder* :predicates (file-finder:extension= "txt")
                       :root (first (find-dir :n-test 1
                                              :keep "Downloads"
                                              :depth 3)))


  ;; wrapper set interpretation is different
  ;; and
  (finder (<ff>)(<ff>))
  ;; or
  (finder (list (<ff>) (<ff>)))

  ;; convert results to string to use set operations
  ;; &&& is there a better way
  (mapcar #'namestring (finder &&&))
  (set-difference *), (union *)

  (set-difference
   (mapcar #'path (finder (path~ "index") (path~ "indices") (extension= "tif")))
   (mapcar #'path (finder (path~ "tiles")))
   :test #'equal)
#+end_src

** command line REPL

$ rlwrapper sbcl #allows readline support on terminal

CL-USER> (print "hello")
"hello" ; standard out
"hello" ; evaluation

=*= references last returned evaluation

** Interfacing emacs/code/REPL
pushing parens ahead around next form
go to source
l to move back in stack trace
slime-cd to change location
* Lisp Operations
** Pathnames

Common Lisp is older than any of the file systems in use today, its pathname
system is still more powerful and still relevant to every possible system. That
is a clue that there are some significant differences in how this is being
acomplished, some will not be intuitive.
https://lispcookbook.github.io/cl-cookbook/files.html
is essential reading, twice.

These tools cover far MORE than linux can acomplish with a filesystem. Clarifying
and reducing initial friction for file and dir ops is one of the major objectives of
this project.
- https://github.com/Shinmera/pathname-utils
- https://edicl.github.io/cl-fad/
- https://github.com/Shinmera/filesystem-utils
- https://shinmera.github.io/file-attributes/
- https://osicat.common-lisp.dev/manual/osicat.html
- https://github.com/fosskers/filepaths
- https://codeberg.org/fourier/ppath
- https://asdf.common-lisp.dev/uiop.html

#+begin_src lisp
                                          ; pathname objects are not strings
  #P"/bin/"
  ;; subcomponents can be manipulated individually
  ;; inspect &&&

  ;; ~ for home
  (user-homedir-pathname)

  ;; . for this location
  (uiop:getcwd)


#+end_src

Override default-pathname-defaults
#+begin_src lisp
  ;; this guy causes issues if Im not paying attention
  (print *default-pathname-defaults*)

  ;; &&&note elsewhere how (print (foo)) is transparent, prints and passes (foo) through
  ;; very nice for debugging

  (uiop:with-current-directory ("/bin")
    (print (uiop:getcwd))
    (directory-files "./"))

  (print (uiop:getcwd))

  (with-current-directory ("/tmp")
    (print (uiop:getcwd)))
#+end_src

** Dir Operations
Some operations use the default-pathname-defaults variable to establish the starting point, not all.
Online commentary defining paths from root is guaranteed consistent. I just set it consistently, it is wrapped in the (cd "str") function.

#+begin_src lisp
  (defparameter *my-starting-dir* (uiop:getcwd))

  ;; ls -d
  (directory "*") ; the syntax is badly documented(online) check

  (uiop:subdirectories (user-homedir-pathname))
  (uiop:subdirectories #P"/home/user/")
  (uiop:subdirectories "/home/user/")

  ;; pwd
  (uiop:getcwd)

  ;; cd
  (uiop:chdir #P"/path/name")
  (setf *default-pathname-defaults*(uiop:getcwd))


  ;; path to string
  (namestring "/home/user/")
  (namestring "#P/home/user/")
  (namestring (user-homedir-pathname))

  ;; string to path
  (pathname "/home/user")
  (pathname "/home/user/")
  (pathname #P"/home/user/")
  (pathname (user-homedir-pathname))


#+end_src

** File Operations

#+begin_src lisp
  ;; ls -f
  (directory-files &&&)

  ;; &&& move rename delete
#+end_src

** File IO

#+begin_src lisp
  (defparameter *file* #p"/home/user/test.txt")
  (print *file*)
  (uiop:read-file-lines *file*)

                                          ; open files
  (with-open-file (stream "test.txt" :direction :output
                                     :if-exists :supersede)
    (write-line "Hello, World!" stream))

  (with-open-file (stream "test.txt"
                          :direction :input
                          :if-does-not-exist :error)
    (let ((contents (make-string (file-length stream))))
      (read-sequence contents stream)
      (print contents)))

  (with-open-file (stream filename)
    (iter (for line = (read-line stream nil))
      (while line)
      (format t "~A%~%" line)))
#+end_src

** Getting Help

quicksearch
https://github.com/lisp-maintainers/quicksearch

TODO (help) and (help "symbol")
should be an interactive menu describing the options/ letting user go on to any or all sub
(help "help") should go give detailed descriptions of each  option

package help
symbol help
namespace help

#+begin_src lisp
  ;;search quicklisp dists for a package
  (ql:system-apropos "find-me")
  ;;search all dists and github for a package
  (quicksearch:quicksearch "find-me")

  ;;inspect
  (inspect "string")
  ;;describe
  (describe "string")
  ;;apropos
  (apropos "string")
  ;;documentation
  (documentation "string")
#+end_src

* Syntax Concepts
Functions within functions within functions. Look inward.
** Parentheses are just trees
Don't look at the parens, look at the indentation and see the tree.
The abstract syntax tree is immediately available to the programmer and to the program

Math example
#+begin_src lisp

  (+ (* 3 4) (- 10 5) (/ 12 (+ 2 2)))

  ;; math is just a tree of operations
  (+ (* 3
        4)
     (- 10
        5)
     (/ 12
        (+ 2
           2)))
#+end_src

Nested lists example
#+begin_src lisp
  (defvar *tree* '(A(B(D)(E))(C(F)(G)(H))))

  ;; data is just a tree of relationships
  (A
   (B
    (D)
    (E))
   (C
    (F)
    (G)
    (H)))
#+end_src

Tree traversal example
#+begin_src lisp
  ;; code is just trees of steps
  (defun traverse (tree)
    (when tree                        ;stops when nothing
      (if (atom tree)                 ;test for a leaf node
          (print tree)                ; true, print the leaf
          (progn                      ; else, do these things
            (print (car tree))        ;  print parent before decending
            (traverse (cdr tree)))))) ;  descend into the remainder of the tree
#+end_src

Q: If code is just trees, and data and calculations are just trees
and we have code that walks into a tree
does that mean a program could go into a program?
could a program treat a program like data and change it?

A: It is just a tree, code is data, data is code.

** Variables
defparameter vs defvar, both set global variables
defparameter is mutable
defvar is immutable

let is lexically scoped, valid within it range
let can dynamically redefine a global variable temporarilly

#+begin_src  lisp
(defparameter *my-param*) ;error requires binding
(defparameter *my-param* nil) ; bound to NIL
(defparameter *my-param* '()) ; bound to NIL
(defparameter *my-param* 42
  "doc for my-param")
(defparameter *my-param* 47
  "doc for my-param") ; rebound


(defvar *my-var*) ; success unbound at this point, not even nil
(defvar *my-var* 124) ; bound at this point
(defvar *my-var* 1) ; immutable, but no error on attempt

(let (a b)
  (setf a 1
        b 2)
  (format t " a: ~A b: ~A~&" a b))
(let ((a 3)
      (b 4 ))
  (format t " a: ~A b: ~A~&" a b))

(let* ((a 3)
       (b 4)
       (c (+ a b)))
  (format t " a: ~A b: ~A c: ~A~&" a b c))

(format t "outside the lexical scope before the let *my-param*: ~A~&" *my-param*)
(let ((*my-param* 11))
  (format t "only within the lexical scope of the let *my-param*: ~A~&" *my-param*))
(format t "outside the lexical scope after the let *my-param*: ~A~&" *my-param*)
#+end_src

** Conditions

#+begin_src  lisp
  (if (test)
      (then) ; or prog1 for then,continuing
      (else))

  (when (test)
    (then)
    (continuing)) ; implicit progn, no else
  ;; (unless) compliment of when

  (not (test)) ; compliment of test


  (cond ; returns first true block
    (test
        logic0
      logic1
      )
    (t :default))

  (case a
    (1
     :its1)
    (t :default))

  ;; conditional on environment
  *features* is a list of keywords anyone can add to it
  (push :my-feature *features*)
  #+unix
  (print "we are on unix")

  #-foo
  (print "of course there is no foo feature")

  #+(and unix my-feature)
  (print "we are on unix working on my-feature")
#+end_src
** args

#+begin_src lisp
  ;; arguments
                                          ;ordered binding
  (defun example-function (required &optional (optional-arg nil optional-arg-supplied-p))
    (if optional-arg-supplied-p
        (format t "Optional argument was supplied: ~A~%" optional-arg)
        (format t "Optional argument was not supplied~%")))
                                          ; :keyword binding
  (defun example-function (&key (keyword-arg nil keyword-arg-supplied-p))
    (if keyword-arg-supplied-p
        (format t "Keyword argument was supplied: ~ A~%" keyword-arg)
        (format t "Keyword argument was not supplied~%")))

  ;; &&& note on the undefined combination ? &optional &rest
  ;; &&& &rest &body etc
#+end_src

** functions

#+begin_src lisp
  ;; declaration
  (defun hello ()
    "docstring for hello"
    (format t "hello ~A" (uiop:getenv "USER")))
  (hello)

  ;; local functions
  (defun example-flet ()
    (flet ((local-func (x) (* x 2)))
      (local-func 5)))

  (defun example-labels ()
    (labels ((a () (print "In A")))
      (a)))

  (defun example-labels-mutual ()
    (labels ((a () (print "In A"))
             (b () (a)))
      (b)))




(defun hello (name &optional happy) ; optional nil by default
  (format t "hello ~A~&" name)
  (if happy ; when truthy
    (format t ":)")
    (format t ":(")))

(defun hello (name &key (happy "default value" happy-p))
  "doc string"
  (format t "hello ~A~&" name)
  (when happy-p ; when supplied
    (if happy
        (format t ":)")
        (format t ":(")) ))

(defun mean (x &rest numbers)
  "compute mean to demonstrate variadic num of args"
  (format t "&rest yields a list. numbers: ~A~&" numbers)
  (/ (apply #'+ x numbers)
     (1+ (length numbers))))

,-h-h slime-describe-symbol
(apropos "hello") ; loaded in image
(documentation 'hello 'function) ; a symbol
(documentation #'hello 'function) ; a function
;; it is meaningfully different to inspect the symbol vs the function
(inspect 'hello) ; show symbol attributes
(inspect #'hello) ; show function bindings
;; additionally ' mostly refers to toplevel bindings while #' respects lexical environment, flet etc
;; a source of subtle bugs
(describe #'hello) ; usually this is what you need

flet is like let, must be independent
labels is like let*, can refer to each other

;;multiple return values
(defun my-multiple-returns ()
  (let ((a 1)
        (b 2)
        (str "my-string"))
    (values a b str)))

  ;; not a list or tuple
(my-multiple-returns) ; => 1, 2, "my-string"
;; the return value is the first of values
CL-USER> * ; => 1
(nth-value 2 (my-multiple-returns))
(multiple-value-bind (0th 1th) ;  bind to local variables in order,  can bind part or all
    (my-multiple-returns)
  (print 0th)
  (print 1th))

;; higher order functions
(defun compute (x y &key (operation #'+))
   (funcall operation x y))
(compute 1 2)
(compute 1 2 :operation #'-)

(member "foo" '("foo" "bar"))
(member "foo" '("foo" "bar") :test #'string-equal)

(lambda (x) (1+ x))
CL-USER> (funcall * 2)

(compute 4 2 :operation (lambda (x y) (+ 10 x y)))

(defun generate-adder (step)
  (lambda (x)
    (+ x step)))

(generate-adder 10)

funcall and apply

;; closures
function closes over the environment

(let ((counter 0))
  (defun counter-inc ()
    (incf counter))
  (defun counter-init ()
      (setf counter 0))
  (defun counter-value ()
    counter))

(counter-inc)
(counter-value)
(counter-init)

;; returning closures
(defun make-looping-counter (limit)
  (let ((counter 0))
    (lambda ()
      (if (>= counter limit)
          (setf counter 0)
          (incf counter)))))
(defparameter *counter-to-2* (make-looping-counter 2))
(funcall *counter-to-2*)
(inspect *counter-to-2*)

;; setf functions
(let ((counter 0))
  (defun counter-inc ()
    (incf counter))
  (defun counter-init ()
      (setf counter 0))
  (defun counter-value ()
    counter)
  (defun (setf counter-value) (new-value) ; reuse accessor, supply value and any accessor arg
    (setf counter new-value)))

(counter-init)
(counter-inc)
(setf (counter-value) 6) ; setf the location provided by the accessor
(counter-value)


#+end_src

** returns

#+begin_src lisp
  ;; let return
  (let ((a 3)) a) ; => 3
#+end_src

** Errors and Handling
#+begin_src lisp

  ;;simple errors
  (error "This is an error message")
  (error "Problem with x=~D and y=~S" x y)
  ;;specific error types:
  (signal 'type-error (list :expected-type 'number :datum "not a number"))
  ;;For custom errors, define a condition and use `error` with it:
  (define-condition my-custom-error (error) ())
  (error 'my-custom-error)

  ;; create an error
  (error "Signals an error. The arg was: ~A" arg)
  (warn "carefull") ; no debugger
  ;; create object
  (make-condition 'simple-condition ) ; type one of: 'warn 'error 'simple-condition
  ;; signal it
  (signal *)
  signal then handle not throw catch

  (ql:quickload :log4cl)
  (defun f1 (&optional (arg 'nil))
    (error "Signals an error. The arg was: ~A" arg))
  (defun f2 ()
    "handle conditions with handle case"
    (handler-case
        (f1)
      (error (c) ; c for the condition we want to handle
        (log:info "We got an error: ~A" c))))

  (defun w1 ()
    (warn "Warning"))
  (defun f2 ()
    "handle conditions with handle case"
    (handler-case
        (w1)
      ;;doesnt catch warnings
      (error (c) ; c for the condition we want to handle
        (log:info "We got an error: ~A" c))
      (warning (c)
        (log:info "we got a warning: ~A" c))))

  ;; catch errors
  ;; handler-case
  ;; define errors
  ;; ignore-errors
  ;; unwind-protect
  ;; handler-bind
#+end_src

** Macros
#+begin_src lisp


macros do not evaluate their arguments, it is passed as is to the macro process
macros expand to function calls at compile time


(defmacro cube (x)
  `(* ,x ,x ,x))
(cube 2)

;;quote
;; quote does not evaluate its argument.

(list 1 a 2 b) ; > error on a unbound
(quote (list 1 a 2 b)) ; > (LIST A etc) list of symbols
'(list 1 a 2 b) ; > same

(list :a 1 :b 2) ; > (:A etc)
'(:a 1 :b 2) ; > same

(quote (list :a 1 :b 2)) ; > (LIST :A etc)
(eval (quote (list :a 1 :b 2))) ; > (:A etc) full circle

(let ((a 1)
      (b 2))
  (list 'a a 'b b)) ; > (A 1 B 2)


;;backquote and comma
;; do not require macros to use bq and comma
(let ((a 1)
      (b 2))
  `(:a ,a :b ,b)) ; > (:A 1 :B 2)

;; how to spot you are using a macro
non reqular lisp syntax eg loop macro
non regular paren nesting eg let
starts with 'with' eg with open file
new variable bindings eg dolist

;;macros vs functions

macros can not  be used as HOF
funcall, mapcar, apply etc
(defmacro cube (x)
  "you dont need a macro for this"
  `(* ,x ,x ,x))
(mapcar #'cube (list 1 2 3 4)) ; > error macro not function

redefining a macro requires recompiling all functions that use it to be updated
a macro is not called at runtime, because it expands to code at compile time
(defmacro madd (x)
  `(+ 1 ,x))
(defun adder (x)
  (madd x))
(adder 1) ; > 2, even if we recompile madd, must recompile adder to update

slime-macroexpand-all will reveal that the macro has been included in the function at compilation
slime-who-calls functions
slime-who-references symbols
slime-who-macroexpands macros
  jumps to a file, which we may C-c C-k  slime-compile-and-load to recompile all
  but you probably dont need a macro. use them lightly

;; comma-splice
does not require a macro to use

(list :params (loop for i to 2 collect i)) ; => (:PARAMS (0 1 2))
`(:params ,@(loop for i to 2 collect i)) ; => (:PARAMS 0 1 2)

(defmacro mrest (@rest rest)
  (format t "rest is: ~S" rest)
  ~(progn
     ,@rest))

;;body

(defmacro with-body (&body body)
  `(progn ,@body))
(with-body
  (print :body))

(defmacro my-dolist ((var expr) &body body)
  `(loop for ,var in ,expr do
         (progn
           ,@body)))
(my-dolist (x '(1 2 3))
  (print x))

;;
(defmacro with-echo (&body body)
  `(format nil "the result of ~S is ~S"
           (quote ,@body)
           (progn ,@body)))
(with-echo (+ 1 1))

;; gensym
subtle bugs due to variable capture without this

;; call-with pattern
makes reasoning and testing macros easier

(defun call-with-repeat (times function)
  (loop for x from 1 to times do
        (funcall function)))
(defmacro repeat (times &body body)
  `(call-with-repeat ,times (lambda () ,@body)))
(let ((x "hi"))
  (repeat 3 (print x)))

;; compile time computing
use to reduce execution calculations and for developer errors at compile time
defun*

;; lists vs AST
CL macros manipulates lists of symbols

;; symbol-macro

;; read time evaluation with #.

;; macro-step
#+end_src

** CLOS
;; pretty printing
;; defclass
;; custom constructors
;; initialize-instance
;; multiple inheritance
;; defgeneric vs defmethod
;; class allocation
** quoting data
** logic
** control
* Shelter Concepts

- Shelter's idea of working directory is completely independent of the rest of the program.
- In fact shelter is designed to be independent of the rest of the image
- its purpose is to be a shelter used to explore files at runtime without making any impact on the running program

* Shelter Operations

 &&&

** Implemented

- builtins that wont be overridden
  - sort
  - time
  - find

1. pwd
2. ls
3. cd
4. which
5. cat
6. head
7. tail

** Not implemented

Listed in priority order from partially completed to planned.

1. rm
2. mv
3. cp
4. touch
5. rmdir
6. mkdir
7. echo
8. chown
9. chmod
10. grep (file grep, needs to map ppcre string matching for composability)
11. wc
12. uniq
13. whoami
14. date
15. uname

I would love to pilfer the best parts of nushell as well

* Interop
** Cmd
Calls to command line, protected and various return types
https://github.com/ruricolist/cmd

#+begin_src lisp
                                          ; Loading
  (ql:quickload :cmd)
  (use-package :cmd)

                                          ; Usage
  ($cmd "ls")
  ($sh "cd ~; ls")
  ($sh "pwd")
  ($cmd "echo a b \
                    c \
                    d")

  ($cmd "echo 'hello world' >> text.txt")
  ($cmd "echo 'hello world' > text.txt")

  (defun call-cmd (arg arg1)
    ($cmd (format nil "echo hello:
                                   ~A
                                   ~A" arg arg1)))
  (call-cmd "Lamb" "Duh")

                                          ; &&& return types
  (cmd "cmd")
  ($cmd "cmd")
  ($sh "cmd")

#+end_src

** py4cl2

Python interop
https://github.com/digikar99/py4cl2

#+begin_src lisp

  (ql:quickload :py4cl2)
  (use-package :py4cl2)

                                          ; first time manually initialize
  ;; (py4cl2:initialize)
  ;; ;; python3, ret, ret, ret
  ;; (print py4cl2:*config*)
  ;; (setf (config-var pycmd) "python3") ; set one field

                                          ; test if pycmd finds python on path
  (py4cl2:pyversion-info)    ; fails if python command is not resolved

                                          ; test usage
  (py4cl2:pyexec "print(\"hello\")")    ; => hello
  (py4cl2:defpymodule "math")
  (py4cl2:pyeval "math.pi")             ; 3.1415...
  (py4cl2:defpymodule "numpy" nil :lisp-package "NP")
  (np:floor 4.2)                        ; => 4.0
  (py4cl2:pyeval "[i**2 for i in range(5)]")

                                          ; import and environment
  (defpymodule "os" nil :lisp-package "OS")
  (defpymodule "sys" nil :lisp-package "SYS")
  (defpymodule "pprint" nil :lisp-package "PPRINT")
  (pyexec "sys.path.append('/home/user/code/dircontainingscript')")
  (pyexec "sys.path.append('/home/user/.local/lib/python3.10/site-packages')")
  (pyexec "sys.path.append('/home/user/.guix-profile/lib/python3.10/site-packages')")
  ;; check python path contains target and path to imported modules
  (pyexec "pprint.pprint(sys.path)")
  (os:getcwd)
  (os:listdir)

                                          ; test setup
  ;; NOTE: files on path cannot have '-' in them or defpymodule fails, with NIL!!!
  ;; NOTE: If the file has a compilation error, then import will return NIL!!!
  ;; NOTE: unresolved module import is one such silent failure mode.
  ;; create pytest.py on python path which contains the following.
  ;; ======================================
  ;; def test():
  ;;     print("test sucessfull")

  ;; def argument(a):
  ;;     print(a)

  ;; def math(x):
  ;;   y = x * x
  ;;   return y
  ;; ======================================

                                          ; test import script on path
  (defpymodule "pytest" nil :lisp-package "PYTEST")
  (pytest:test)
  (pytest:argument :a "hello")
  (pytest:argument :a 42)
  (pytest:math :x 9)
  ;; must stop and restart to re import with changes

                                          ; stop
  (py4cl2:pystop)
  (py4cl2:python-alive-p)

#+end_src

** Clesh
https://github.com/Neronus/clesh
clesh is included here mostly to show off how
flexible lisp can be, this is almost unthinkable in other languages, yet it is
transparently available without core language changes.

I recommend using cmd over clesh for permanent work, but for experimental, fast
tasks, scripts etc this mixed inlining is very handy indeed. cmd is more
controlable and disciplined and better suited for wrapping calls for serious
use.

#+begin_src lisp
                                          ; load
  (ql:quickload :clesh)
  (use-package :named-readtables)
  (in-readtable clesh:syntax)

                                          ; usage
  ;; repl out
  !ls
  !echo ?(+ 2 3) foo 5 bar

  ;;messages out
  [echo one two three] ;call bash command
  [echo one ?(+ 1 1) three] ;call lisp command in bash command
  (princ [echo foo]) ;call bash command in lisp command

  (defparameter *val* 42)
  [echo one ?*val* three] ;sub lisp var in bash arg
  [echo one ?(princ *val*) three] ;sub lisp command in bash arg

  ;; break bash commands
  [echo one \
  two \
  three]

  (princ [echo one \
         ?*val* \
         three]) ;sub lisp var in bash arg

  (princ [echo one \
         ?(+ *val* *val*) \
         three]) ;sub lisp command in bash arg

  ;; within a function
  (defun call-clesh (arg arg1)
    [echo \
    Hello: \
    ?arg \
    "FOO" ?arg1])
  (call-clesh "Lamb" "Duh")
#+end_src

** Scripting with CL
*** guides

-  sly adapted as shell https://web.archive.org/web/20210730202847/https://ambrevar.xyz/lisp-repl-shell/index.html
- https://simonsafar.com/2021/lisp_scripting/
- https://fare.livejournal.com/184127.html
- https://atomized.org/blog/2020/07/06/common-lisp-in-practice/
- shell wrapper https://www.cliki.net/CL-Launch

*** command line args

unix-opts
https://github.com/libre-man/unix-opts

The UNIX command line args can be read from the variable =sb-ext:*posix-argv*=

*** export binaries

(uiop/image: &&&)

** &&& clojure R etc
TODO Unified example of library interop, and program interop to minimal program with one argument for each lang
* Select Systems

Some examples are provided.

** strings

str
https://github.com/vindarel/cl-str

(str:split " " "hello world") ; => ("hello" "world")
(str:replace-all old new string)
(str:lines &&&)

regex
https://edicl.github.io/cl-ppcre/

time
https://local-time.common-lisp.dev/

** testing
https://github.com/lmj/1am
https://github.com/AccelerationNet/lisp-unit2
** GUI

clog common lisp omnificient gui
https://rabbibotton.github.io/clog/cltt.pdf

** logging

https://github.com/7max/log4cl

** iteration
*** built in

#+begin_src lisp
  ;;dotimes
  (dotimes (n 3)
    (print n))

  ;;dolist
  (dolist (i '(1 2 3))
    (print i))

  ;;mapcar
  (mapcar #'print '(1 2 3))

  ;; There is also the built in loop macro, its syntax is powerful, but non idiomatic
#+end_src

*** iterate

https://iterate.common-lisp.dev

#+begin_src lisp
  (ql:quickload :iterate)
  (use-package :iterate)

  (iterate:display-iterate-clauses)

  (defparameter *my-vector* #(1.1 2.2 3.3 4.4))
  (defparameter *my-list* '(1 2 3 4))

  (defparameter *my-hashtable* (make-hash-table))
  (setf (gethash 'a *my-hashtable*) 10)
  (setf (gethash 'b *my-hashtable*) 20)
  (setf (gethash 'c *my-hashtable*) 30)

  ;; hashtables
  (iter (for (k v) in-hashtable *my-hashtable*)
    (collect (cons k v)))

  ;; List iteration
  (iter (for i in *my-list*)
    (collect i))

  ;; Vector iteration
  (iter (for v in-vector *my-vector*)
    (collect v))

  ;; ranges
  (iter (for i from 1 to 10)
    (collect i))
  (for i upfrom 0)
  (for i from 5)
  (for i downfrom 0)
  (for i from  1 to 10)
  (for i from 1 below 10)
  (for i from 1 to 10 by 2)
  (for i from 10 downto 1)

  ;; Nested iterations:
  (iter outer (for i from 1 to 3)
    (iter (for j from 1 to 3)
      (in outer (collect (list i j)))))

  ;; Conditional collection:
  (iter (for i from 1 to 10)
    (when (evenp i)
      (collect i)))

  ;; Summing:
  (iter (for i in '(1 2 3 4 5))
    (sum i))

  ;; Finding maximum:
  (iter (for i in '(3 7 2 9 1))
    (maximize i))

  ;; String iteration:
  (iter (for char in-string "Hello")
    (collect (char-upcase char)))

  ;; Iterating with multiple variables:
  (iter (for i from 1 to 5)
    (for j from 10 downto 6)
    (collect (list i j)))

  (iter (for i from 1 to 5)
    (for j from 1 to i)
    (collect (list i j))) &&&

  ;; Early termination:
  (iter (for i from 1)
    (while (< i 5))
    (collect i))

                                            ; Simple iteration over a range:
    (iter (for i from 1 to 10)
      (sum i))

                                            ; Simple iteration over a list:
    (iter (for x in '(1 2 3 4 5))
      (sum x))

                                            ; Iterating over a range of numbers:
    (iter (for i from 1 to 5)
      (collect (* i i)))

    (iter (for i from 1 to 5)
      (sum (* i i)))

                                            ; Iterating over a hash table:
    (let ((ht (make-hash-table)))
      (setf (gethash 'a ht) 1
            (gethash 'b ht) 2
            (gethash 'c ht) 3)
      (iterate (for (k v) in-hashtable ht)
        (collect (list k v))))
                                            ; => ((C 3) (B 2) (A 1))

                                            ; Nested iteration:
    (iter (for i from 1 to 3)
      (collect (iterate (for j from 1 to i)
                 (collect j))))
                                            ; => ((1) (1 2) (1 2 3))
#+end_src

** event scheduling
*** shelter

&&& Initialization functions custom to shelter
- on-start
- on-project

*** clerk

#+begin_src lisp
  (ql:quickload :clerk)
  (use-package :clerk)

  ;; Make sure your jobs are loaded before executing (clerk:start)
  ;; &&&verify
  (clerk:job "Say 'Hello' often" every 5.seconds (print "Hello"))
  (clerk:start)
  (clerk:stop)

  (defun bark ()
    (print "Bark!"))

  (clerk:job "The dog barks" every 7.seconds (bark))
  (clerk:start)
  (clerk:stop)

  ;; The jobs reside inside clerk:*jobs*,
  (dolist (j clerk:*jobs*)
    (print j))
  ;; list of all scheduled and running jobs.
  (clerk:calendar)

  (clerk:empty-jobs-queue)
  (clerk:calendar)

  ;; all examples above are continuous jobs, set with every
  ;; one time jobs are also available
  ;; use in  or after to set one time jobs
  (clerk:job "Say 'Hello' often" every 5.seconds (print "Hello"))
  (clerk:start)
  (clerk:job "Bark once" in 15.seconds (bark))
  (clerk:calendar)
  (clerk:stop)
  (clerk:empty-jobs-queue)

  ;;programmatic setup
  (defparameter *query-interval* 30)
  (clerk:job-function (format nil "Task set for every: ~A seconds" *query-interval*)
                      'every `(,*query-interval* seconds)
                      #'bark) ; requires a function symbol or lambda
#+end_src

Intervals

interval-type is one of the following (plural is equivalent, ie minute = minutes):
second minute hour day week month year
=<+ve integer>.<interval>=

or Days of the week
if you type the day of the week, clerk will calculate when it is and add an event to the queue.
=(job "Weekly report" every monday (create-report))=

** database

mito
https://github.com/fukamachi/mito

** math

in hyperspec as numbers
https://novaspec.org/cl/12_1_Number_Concepts

** data structures

reading
- https://blog.djhaskin.com/blog/common-data-structures-in-common-lisp/

access uniformity
https://github.com/AccelerationNet/access/

fset
https://github.com/slburson/fset

gmap
https://github.com/slburson/misc-extensions

listopia
https://github.com/Dimercel/listopia

*** a and p lists

&&&

*** hashtables

#+begin_src lisp
                                          ; Creating and using a simple hashtable:
  (defvar *fruit-prices* (make-hash-table :test #'equal))

  (setf (gethash "apple" *fruit-prices*) 0.50)
  (setf (gethash "banana" *fruit-prices*) 0.75)

  (format t "An apple costs $~A~%" (gethash "apple" *fruit-prices*))

                                          ; Using gethash with a default value:
  (defvar *user-scores* (make-hash-table))

  (setf (gethash "Alice" *user-scores*) 100)

  (format t "Bob's score: ~A~%" (gethash "Bob" *user-scores* 0))

                                          ; Iterating over a hashtable:
  (defvar *capitals* (make-hash-table :test #'equal))
  (setf (gethash "France" *capitals*) "Paris"
        (gethash "Japan" *capitals*) "Tokyo")

  (maphash #'(lambda (country capital)
               (format t "The capital of ~A is ~A~%" country capital))
           ,*capitals*)

                                          ; Removing an entry and checking the count:
  (defvar *inventory* (make-hash-table))
  (setf (gethash 'book *inventory*) 5
        (gethash 'pen *inventory*) 10)

  (remhash 'book *inventory*)
  (format t "Items in inventory: ~A~%" (hash-table-count *inventory*))
#+end_src

** data formats IO

json
https://github.com/Zulu-Inuoe/jzon/

csv
https://github.com/AccelerationNet/cl-csv

xlsx
https://github.com/defunkydrummer/lisp-xl
on github &&& install notes

** distribution

*** quicklisp

https://www.quicklisp.org/beta/
https://common-lisp-libraries.readthedocs.io/quicklisp/

- quicklisp links to docs https://quickref.common-lisp.net/index-per-library.html
- quicklisp catalogue https://www.quicklisp.org/beta/UNOFFICIAL/docs/
- quicklisp search https://quickdocs.org/

#+begin_src lisp

  ;; check installed dists
  (ql-dist:all-dists)

  ;; &&&note on
  (quicklisp:update-all-dists)

  ;; &&& how to uninstal dists
  ;; &&&reinstall dists
#+end_src

*** ultralisp
https://ultralisp.org/
*** ocicl
https://github.com/ocicl/ocicl
*** asdf
https://asdf.common-lisp.dev/
* Software Sources

ocicl libraries list
https://raw.githubusercontent.com/ocicl/request-system-additions-here/main/all-ocicl-systems.txt

quick lisp libraries list
https://quickref.common-lisp.net/index-per-library.html

ultralisp libraries list
https://dist.ultralisp.org/ gets you the latest distinfo as a file
https://dist.ultralisp.org/ultralisp/20260819025001/systems.txt gets the list of packages as a file

common lisp hosting
https://common-lisp.net/
https://common-lisp.net/phub

* Resources
** essential links

use the cookbook
https://lispcookbook.github.io/cl-cookbook/

hyperspec
https://www.lispworks.com/documentation/HyperSpec/Front/

novaspec
https://novaspec.org/cl/

minispec
https://lamberta.github.io/minispec/

** common common lisp functions
- &&& extract outline of minispec
** important systems
*** uiop
- manual https://asdf.common-lisp.dev/uiop.html
- &&& list of functions available
*** asdf
- defacto docs https://asdf.common-lisp.dev/
- manual https://www.sbcl.org/asdf/
- &&& list of functions available
*** alexandria
- defacto docs https://alexandria.common-lisp.dev/draft/alexandria.html
- manual https://alexandria.common-lisp.dev/draft/alexandria.html
- &&& list of functions available
*** serapeum
- github https://github.com/ruricolist/serapeum
- manual https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md
- &&& list of functions available

** lists of packages

- awesome common lisp list https://github.com/CodyReichert/awesome-cl
- common lisp wiki, almost every CL package https://www.cliki.net/
- another lisp https://common-lisp.net/libraries
- defacto libraries docs page https://common-lisp-libraries.readthedocs.io/
  - asdf - Build System
  - alexandria - Commonly Used Utilities
  - bordeaux-threads - Threading
  - cl-ppcre - Regular Expressions
  - cl-who - DSL for Markup
  - fiveam - Regression Testing Framework
  - hunchentoot - Web Server
  - iterate - Psuedocodic Iteration
  - local-time - Date and Time Manipulation
  - postmodern - PostgreSQL programming interace
  - quicklisp - Library Manager
  - usocket - Universal Socket Library
  - utilities - A collection of utility libraries
  - numcl - Lispy clone of numpy
  - unix-opts - cmd line argument parser

** programming guides

- syntax crash course https://learnxinyminutes.com/docs/common-lisp/
- lisp crash course https://cs.gmu.edu/~sean/lisp/LispTutorial.html
- great teacher https://stevelosh.com/blog/2018/08/a-road-to-common-lisp/
- learn lisp the hard way https://llthw.common-lisp.dev/
- another terser cookbook https://cl-cookbook.sourceforge.net/index.html
- common lisp by example http://csci.viu.ca/~wesselsd/courses/csci330/code/sbcl-lisp/index.html
- successful lisp book https://dept-info.labri.fr/~strandh/Teaching/MTP/Common/David-Lamkins/contents.html

** learn by watching

- https://www.youtube.com/@the-lisper/videos
- https://www.youtube.com/watch?v=0RQYa2XJBKU
- https://www.youtube.com/@philipbohun740/videos
- https://www.youtube.com/watch?v=rmUTW5QWhhM&list=PL2VAYZE_4wRJi_vgpjsH75kMhN4KsuzR_&index=2

** reference

- sbcl man http://www.sbcl.org/manual
- technical syntax quick reference http://clqr.boundp.org/clqr-a4-consec.pdf
- documentation redirect service http://l1sp.org/html/
- googles lisp style guide https://google.github.io/styleguide/lispguide.xml
- style guide http://mumble.net/~campbell/scheme/style.txt

** heavy hitters

some seriously potent programmers

- lisp-maintainers https://github.com/vindarel/lisp-maintainers
- sharp lispers https://github.com/sharplispers
- shinmera https://codeberg.org/shinmera/
- fukamachi https://github.com/fukamachi
- vindarel https://github.com/vindarel/
- robert smith https://github.com/stylewarning
- ruricolist https://github.com/ruricolist

** reading

- advanced functional programming https://www2.cs.sfu.ca/CourseCentral/310/pwfong/Lisp/2/tutorial2.html
- page 13 explained in pythoooon https://michaelnielsen.org/ddi/lisp-as-the-maxwells-equations-of-software/
- page 13 in modern scheme https://www.gnu.org/software/mes/manual/html_node/LISP-as-Maxwell_0027s-Equations-of-Software.html
- LOL book https://letoverlambda.com/index.cl/toc
- blog and lisp bibliography https://simondobson.org/writing/
- lisp nn from primitives https://woodrush.github.io/blog/posts/2022-01-16-neural-networks-in-pure-lisp.html
- interactive programming implications https://www.n16f.net/blog/interactive-common-lisp-development/

** citations

- https://www.math.fau.de/wp-content/uploads/2020/09/Preprint-2002-40-scan.pdf
- &&& bring other lisp citations here!

* CLEAN
Common Lisp Environment for Experiment and Analysis

All advanced data science ML and modelling goes here
If shelter is the living room clean is the laboratory

I want an operating system for data science,
deployable pipelines and experiment tracking is the goal

declarative file system state
https://github.com/Virtual-Insurance-Products/cl-sysop

Depot
file system protocol browse read write with locks and ACID safety
https://shinmera.github.io/depot/

clml machine learning
https://github.com/mmaul/clml

cl-ana
data frames stats and dependency oriented programming
https://github.com/ghollisjr/cl-ana/wiki

memoization
https://github.com/AccelerationNet/function-cache

ML
https://github.com/melisgl/mgl

nvidia interop
https://github.com/takagi/cl-cuda

lispstat - linear algebra - stats - plot
https://lisp-stat.dev/
#+begin_src lisp
                                          ; RE bug on loading in guix
                                          ; Cffi path Ref: https://lists.gnu.org/archive/html/bug-guix/2020-01/msg00133.html
(ql:quickload :lisp-stat) ; stats

                                          ; usage&&&
#+end_src

deep learning matrices matrices
https://github.com/hikettei/cl-waffe2

syntax modification useful for data pipelines
https://quickref.common-lisp.net/arrows.html

numcl, numpy clone
https://numcl.github.io/numcl/
#+begin_src lisp
                                          ; Creating and manipulating arrays:
  (numcl:array '(1 2 3 4 5))  ; Create a 1D array
  (numcl:zeros '(3 3))        ; Create a 3x3 array of zeros
  (numcl:aref my-array 1 2)   ; Access element at row 1, column 2

                                          ; Basic operations:
  (numcl:+ (numcl:array '(1 2 3)) (numcl:array '(4 5 6)))  ; Element-wise addition
  (numcl:* (numcl:array '(1 2 3)) 2)                       ; Scalar multiplication

                                          ; Mathematical functions:
  (numcl:sin (numcl:array '(0 (/ pi 2) pi)))  ; Element-wise sine
  (numcl:exp (numcl:array '(0 1 2)))          ; Element-wise exponential

                                          ; Linear algebra:
  (numcl:matmul matrix1 matrix2)  ; Matrix multiplication
  (numcl:transpose my-matrix)     ; Matrix transposition
#+end_src

&&& gnu scientific library for cl

System info
https://github.com/Shinmera/machine-state/

** lparallel

#+begin_src lisp
                                          ; lparallel startup
  (ql:quickload :lparallel)
  (use-package :lparallel)
  (setf lparallel:*kernel* (lparallel:make-kernel 8)) ;set worker threads

                                          ; env setup for examples
  (defun gt-five (x)
    (if (> x 5)
        x))

  (defun lt-five (x)
    (if (< x 5)
        x))

  (defparameter *mylist* '(0 1 2 3 4 5 6 7 8 9 10) )

                                          ; usage
  (pmap 'list (lambda (x) (* x x)) '(1 2 3 4))
  (preduce #'+ #(1 2 3 4 5))

  (premove '5 '(1 2 3 4 5 6 7 8 9 0))

  (premove-if (lambda (x) (> x 5)) '(0 1 2 3 4 5 6 7 8 9 10))
  (premove-if #'gt-five '(0 1 2 3 4 5 6 7 8 9 10))
  (premove-if #'gt-five *mylist*)

  (premove-if-not #'gt-five *mylist*)
  (premove-if #'gt-five *mylist*)
  (premove-if #'lt-five *mylist*)
  (premove-if-not #'lt-five *mylist*)

  (defun my-filter (predicate list)
    (reduce 'nreconc
            (lparallel:preduce-partial (lambda (acc x)
                                         (if (funcall predicate x)
                                             acc
                                             (cons x acc)))
                                       list
                                       :initial-value nil)
            :initial-value nil
            :from-end t))

  (my-filter #'gt-five *mylist*)
  #+end_src

** generators

gtwiwtg - generators the way I want them generated
https://github.com/d3v3l0/gtwiwtg
https://cicadas.surf/cgit/colin/gtwiwtg.git/about/
clear and modernized and documented


series
https://github.com/rtoy/cl-series
A high quality high perf, classic lib but docs and examples are hard to find

** types

coalton
https://github.com/coalton-lang/coalton/
